;;;; ./demos/dialog/toggle/toggle-01/toggle-01.lisp

(in-package :mnas-sdl3-gui/demos/dialog/toggle-01)

(defparameter *window* nil)
(defparameter *renderer* nil)
(defparameter *window-id* 0)
(defparameter *layer-manager* nil)
(defparameter *toolbar* nil)
(defparameter *open* t)
(defparameter *style* :windows)
(defparameter *widgets* nil)
(defparameter *status* "Выберите переключатель в любой группе.")
(defparameter *status-y* 0)
(defparameter +toolbar-height+ 32)
(defparameter +margin+ 16)
(defparameter +status-band+ 26)
(defparameter +section-gap+ 8)
(defparameter +window-width+ 500)
(defparameter +window-height+ 322)

(defparameter +command-map+
  '((:toggle-01/group-1-option-1 :group-1 "Вариант 1" :one)
    (:toggle-01/group-1-option-2 :group-1 "Вариант 2" :two)
    (:toggle-01/group-1-option-3 :group-1 "Вариант 3" :three)
    (:toggle-01/group-1-option-4 :group-1 "Вариант 4" :four)
    (:toggle-01/group-2-option-1 :group-2 "Опция 1" :q)
    (:toggle-01/group-2-option-2 :group-2 "Опция 2" :w)
    (:toggle-01/group-2-option-3 :group-2 "Опция 3" :e)
    (:toggle-01/group-2-option-4 :group-2 "Опция 4" :r)))
