;;;; ./src/widgets/methods/grid-layout.lisp

(in-package :mnas-sdl3-gui/widgets)

;; Improved grid layout: support spans, weights and alignment (start/center/end/fill)

(defmethod widget-arrange ((grid grid-container) x y width height)
  (place-widget grid :x x :y y :width width :height height)
  (let* ((rows (max 1 (grid-rows grid)))
         (cols (max 1 (grid-cols grid)))
         (spacing-x (grid-col-spacing grid))
         (spacing-y (grid-row-spacing grid))
         (padding (grid-padding grid))
         (inner-x (+ (widget-x grid) padding))
         (inner-y (+ (widget-y grid) padding))
         (inner-w (max 1 (- (widget-width grid) (* 2 padding))))
         (inner-h (max 1 (- (widget-height grid) (* 2 padding))))
         (col-min (make-array cols :initial-element 0))
         (row-min (make-array rows :initial-element 0))
         (col-weights (make-array cols :initial-element 0.0))
         (row-weights (make-array rows :initial-element 0.0)))
    ;; recompute minimal sizes (same logic as measure)
    (dolist (pair (grid-child-constraints grid))
      (let* ((child (car pair)) (c (cdr pair)))
        (multiple-value-bind (min-w min-h) (widget-min-size child)
          (let* ((col (max 0 (min (1- cols) (grid-child-col c))))
                 (row (max 0 (min (1- rows) (grid-child-row c))))
                 (cspan (max 1 (min cols (grid-child-col-span c))))
                 (rspan (max 1 (min rows (grid-child-row-span c)))))
            (let* ((cur-w (reduce #'+ (subseq col-min col (min cols (+ col cspan))) :initial-value 0))
                   (cur-h (reduce #'+ (subseq row-min row (min rows (+ row rspan))) :initial-value 0)))
              (when (< cur-w min-w)
                (let* ((extra (- min-w cur-w))
                       (per (max 1 (floor (+ extra cspan -1) cspan))))
                  (loop for i from col below (min cols (+ col cspan)) do
                    (incf (aref col-min i) per))))
              (when (< cur-h min-h)
                (let* ((extra (- min-h cur-h))
                       (per (max 1 (floor (+ extra rspan -1) rspan))))
                  (loop for j from row below (min rows (+ row rspan)) do
                    (incf (aref row-min j) per))))
              ;; accumulate weights (distribute equally across spanned tracks)
              (let ((wx (grid-child-weight-x c)) (wy (grid-child-weight-y c)))
                (when (> wx 0)
                  (let ((share (/ wx (float cspan))))
                    (loop for i from col below (min cols (+ col cspan)) do
                      (incf (aref col-weights i) share))))
                (when (> wy 0)
                  (let ((share (/ wy (float rspan))))
                    (loop for j from row below (min rows (+ row rspan)) do
                      (incf (aref row-weights j) share)))))))))

      ;; compute available extra space and distribute according to weights
      (let* ((total-min-w (reduce #'+ col-min))
             (total-min-h (reduce #'+ row-min))
             (used-w (+ total-min-w (* spacing-x (max 0 (1- cols)))))
             (used-h (+ total-min-h (* spacing-y (max 0 (1- rows)))))
             (extra-w (max 0 (- inner-w used-w)))
             (extra-h (max 0 (- inner-h used-h)))
             (total-col-weight (reduce #'+ col-weights :initial-value 0.0))
             (total-row-weight (reduce #'+ row-weights :initial-value 0.0))
             (col-widths (make-array cols :initial-element 0))
             (row-heights (make-array rows :initial-element 0)))
        ;; base widths = min
        (dotimes (i cols) (setf (aref col-widths i) (aref col-min i)))
        (dotimes (j rows) (setf (aref row-heights j) (aref row-min j)))
        ;; distribute extra width
        (if (> extra-w 0)
            (if (> total-col-weight 0)
                (dotimes (i cols)
                  (incf (aref col-widths i) (round (* extra-w (/ (aref col-weights i) total-col-weight)))))
                ;; equal distribution
                (let ((base (floor (/ extra-w (max 1 cols)))))
                  (dotimes (i cols) (incf (aref col-widths i) base))
                  (loop for r from 0 below (mod extra-w cols) do
                    (incf (aref col-widths r) 1)))))
        ;; distribute extra height
        (if (> extra-h 0)
            (if (> total-row-weight 0)
                (dotimes (j rows)
                  (incf (aref row-heights j) (round (* extra-h (/ (aref row-weights j) total-row-weight)))))
                (let ((base (floor (/ extra-h (max 1 rows)))))
                  (dotimes (j rows) (incf (aref row-heights j) base))
                  (loop for r from 0 below (mod extra-h rows) do
                    (incf (aref row-heights r) 1)))))

        ;; compute prefix offsets
        (let ((col-x (make-array cols :initial-element 0))
              (row-y (make-array rows :initial-element 0)))
          (let ((acc inner-x))
            (dotimes (i cols)
              (setf (aref col-x i) acc)
              (incf acc (+ (aref col-widths i) spacing-x))))
          (let ((acc inner-y))
            (dotimes (j rows)
              (setf (aref row-y j) acc)
              (incf acc (+ (aref row-heights j) spacing-y))))

          ;; arrange children with halign/valign handling
          (dolist (pair (grid-child-constraints grid))
            (let* ((child (car pair)) (c (cdr pair))
                   (col (max 0 (min (1- cols) (grid-child-col c))))
                   (row (max 0 (min (1- rows) (grid-child-row c))))
                   (cspan (max 1 (min cols (grid-child-col-span c))))
                   (rspan (max 1 (min rows (grid-child-row-span c))))
                   (alloc-w (+ (reduce #'+ (subseq col-widths col (+ col cspan)) :initial-value 0)
                               (* spacing-x (max 0 (1- cspan)))))
                   (alloc-h (+ (reduce #'+ (subseq row-heights row (+ row rspan)) :initial-value 0)
                               (* spacing-y (max 0 (1- rspan)))))
                   (x-off (aref col-x col))
                   (y-off (aref row-y row))
                   (halign (grid-child-halign c))
                   (valign (grid-child-valign c)))
              (multiple-value-bind (min-w min-h) (widget-min-size child)
                ;; compute child size
                (let* ((child-w (if (eq halign :fill) alloc-w (min alloc-w min-w)))
                       (child-h (if (eq valign :fill) alloc-h (min alloc-h min-h)))
                       (child-x (cond ((eq halign :start) x-off)
                                      ((eq halign :center) (+ x-off (floor (/ (- alloc-w child-w) 2))))
                                      ((eq halign :end) (+ x-off (- alloc-w child-w)))
                                      (t x-off)))
                       (child-y (cond ((eq valign :start) y-off)
                                      ((eq valign :center) (+ y-off (floor (/ (- alloc-h child-h) 2))))
                                      ((eq valign :end) (+ y-off (- alloc-h child-h)))
                                      (t y-off))))
                  (widget-arrange child child-x child-y (max 1 child-w) (max 1 child-h)))))))))
    )
  )
  
