;;;; ./src/widgets/methods/handle-widget-key-press.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod handle-widget-key-press :around ((widget widget) key char)
  (declare (ignore key char))
  (when (and (widget-enabled widget) (widget-visible widget))
    (call-next-method)))

(defmethod handle-widget-key-press ((widget widget) key char)
  (declare (ignore key char))
  nil)

(defmethod handle-widget-key-press ((widget button) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget toggle) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget check-box) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget edit-box) key char)
  (cond
    ((eq key :backspace)
     (unless (edit-box-delete-selection widget)
       (when (> (edit-box-cursor widget) 0)
         (let ((text (edit-box-text widget)))
           (setf (edit-box-text widget)
                 (concatenate 'string
                              (subseq text 0 (1- (edit-box-cursor widget)))
                              (subseq text (edit-box-cursor widget))))
           (decf (edit-box-cursor widget))
           (edit-box-ensure-cursor-visible widget)
           (update-widget-value widget (edit-box-text widget)))))
     t)
    ((eq key :delete)
     (unless (edit-box-delete-selection widget)
       (when (< (edit-box-cursor widget) (length (edit-box-text widget)))
         (let ((text (edit-box-text widget)))
           (setf (edit-box-text widget)
                 (concatenate 'string
                              (subseq text 0 (edit-box-cursor widget))
                              (subseq text (1+ (edit-box-cursor widget)))))
           (edit-box-ensure-cursor-visible widget)
           (update-widget-value widget (edit-box-text widget)))))
     t)
    ((eq key :left)
     (when (> (edit-box-cursor widget) 0)
       (decf (edit-box-cursor widget)))
     (clear-edit-box-selection widget)
     (edit-box-ensure-cursor-visible widget)
     t)
    ((eq key :right)
     (when (< (edit-box-cursor widget) (length (edit-box-text widget)))
       (incf (edit-box-cursor widget)))
     (clear-edit-box-selection widget)
     (edit-box-ensure-cursor-visible widget)
     t)
    ((eq key :home)
     (setf (edit-box-cursor widget) 0)
     (clear-edit-box-selection widget)
     (edit-box-scroll-to-start widget)
     t)
    ((eq key :end)
     (setf (edit-box-cursor widget) (length (edit-box-text widget)))
     (clear-edit-box-selection widget)
     (edit-box-scroll-to-end widget)
     t)
    ((member key '(:pageup :pagedown))
     t)
    ((characterp char)
     (edit-box-delete-selection widget)
     (when (< (length (edit-box-text widget)) (edit-box-max-length widget))
       (let ((text (edit-box-text widget)))
         (setf (edit-box-text widget)
               (concatenate 'string
                            (subseq text 0 (edit-box-cursor widget))
                            (string char)
                            (subseq text (edit-box-cursor widget))))
         (incf (edit-box-cursor widget))
         (edit-box-ensure-cursor-visible widget)
         (update-widget-value widget (edit-box-text widget))))
     t)
    (t nil)))

(defmethod handle-widget-key-press ((widget list-box) key char)
  (declare (ignore char))
  (cond
    ((eq key :up)
     (when (> (list-box-selected-index widget) 0)
       (decf (list-box-selected-index widget))
       (update-widget-value widget (nth (list-box-selected-index widget)
                                        (list-box-items widget))))
     t)
    ((eq key :down)
     (when (< (1+ (list-box-selected-index widget))
              (length (list-box-items widget)))
       (incf (list-box-selected-index widget))
       (update-widget-value widget (nth (list-box-selected-index widget)
                                        (list-box-items widget))))
     t)
    (t nil)))