;;;; ./src/widgets/methods/handle-keyboard-event.lisp

(in-package :mnas-sdl3-gui/widgets)

(defstruct (widget-keyboard-input
             (:constructor make-widget-keyboard-input%))
  key
  char
  mods
  ctrl
  shift
  alt
  on-escape
  on-return)

(defun make-widget-keyboard-input (key char &key mods ctrl shift alt on-escape on-return)
  (make-widget-keyboard-input%
   :key key
   :char char
   :mods mods
   :ctrl ctrl
   :shift shift
   :alt alt
   :on-escape on-escape
   :on-return on-return))

(defun normalize-keyboard-event (ev)
  (etypecase ev
    (sdl3:keyboard-event
     (let* ((mods (slot-value ev 'sdl3:%mod))
            (ctrl (key-modifier-active-p mods :ctrl))
            (shift (key-modifier-active-p mods :shift))
            (alt (key-modifier-active-p mods :alt)))
       (make-widget-keyboard-input (slot-value ev 'sdl3:%key) nil
                                   :mods mods
                                   :ctrl ctrl
                                   :shift shift
                                   :alt alt)))
    (widget-keyboard-input ev)
    (null (make-widget-keyboard-input nil nil))
    (symbol (make-widget-keyboard-input ev nil))
    (character (make-widget-keyboard-input nil ev))
    (t (make-widget-keyboard-input nil nil))))

(defmethod handle-keyboard-event (null ev)
  (declare (ignore ev))
  :continue)

(defmethod handle-keyboard-event ((widgets cons) (ev sdl3:keyboard-event))
  (let* ((down (slot-value ev 'sdl3:%down))
         (repeat (slot-value ev 'sdl3:%repeat))
         (key (slot-value ev 'sdl3:%key))
         (mods (slot-value ev 'sdl3:%mod)))
    (cond
      ((not down)
       :continue)
      (repeat
       :continue)
      (t
       (let* ((input (normalize-keyboard-event ev))
              (shortcut-handled-p (mnas-sdl3-gui/commands:dispatch-shortcut
                                   key
                                   :mods (remove nil (list (when (widget-keyboard-input-ctrl input) :ctrl)
                                                           (when (widget-keyboard-input-shift input) :shift)
                                                           (when (widget-keyboard-input-alt input) :alt)))
                                   :context (list :window-id (slot-value ev 'sdl3:%window-id)))))
         (if shortcut-handled-p
             :continue
             (handle-keyboard-event widgets input)))))))

(defmethod handle-keyboard-event ((widgets cons) (input widget-keyboard-input))
  (let* ((focused (focused-widget widgets))
         (key (widget-keyboard-input-key input))
         (mods (widget-keyboard-input-mods input)))
    (cond
      ((and (typep focused '<combo-box>)
            (<combo-box>-expanded-p focused)
            (member key '(:escape :return)))
       (handle-keyboard-event focused input)
       :continue)
      ((eq key :escape)
       (if (widget-keyboard-input-on-escape input)
           (funcall (widget-keyboard-input-on-escape input))
           :continue))
      ((eq key :tab)
       (move-widget-focus widgets :backward (tab-navigation-backward-p mods))
       :continue)
      ((eq key :return)
       (if (widget-keyboard-input-on-return input)
           (funcall (widget-keyboard-input-on-return input))
           :continue))
      ((eq key :space)
       (when focused
         (handle-keyboard-event focused input))
       :continue)
      (t
       (when focused
         (handle-keyboard-event focused input))
       :continue))))

(defmethod handle-keyboard-event ((widgets cons) (ev symbol))
  (handle-keyboard-event widgets (normalize-keyboard-event ev)))

(defmethod handle-keyboard-event ((widgets cons) (ev character))
  (handle-keyboard-event widgets (normalize-keyboard-event ev)))

(defmethod handle-keyboard-event :around ((widget <widget>) ev)
  (declare (ignore ev))
  (when (and (enabled-p widget) (visible-p widget))
    (call-next-method)))

(defmethod handle-keyboard-event ((widget <widget>) (ev sdl3:keyboard-event))
  (handle-keyboard-event widget (normalize-keyboard-event ev)))

(defmethod handle-keyboard-event ((widget <widget>) (ev widget-keyboard-input))
  (declare (ignore ev))
  nil)

(defmethod handle-keyboard-event ((widget <widget>) (ev symbol))
  (handle-keyboard-event widget (normalize-keyboard-event ev)))

(defmethod handle-keyboard-event ((widget <widget>) (ev character))
  (handle-keyboard-event widget (normalize-keyboard-event ev)))

(defmethod handle-keyboard-event ((widget <widget-container>) ev)
  (let ((focused-child (find-if #'<widget>-focused (children widget))))
    (when focused-child
      (handle-keyboard-event focused-child ev))))

(defmethod handle-keyboard-event ((widget <button>) (ev widget-keyboard-input))
  (when (eq (widget-keyboard-input-key ev) :space)
    (activate-widget widget)))

(defmethod handle-keyboard-event ((widget <toggle>) (ev widget-keyboard-input))
  (when (eq (widget-keyboard-input-key ev) :space)
    (activate-widget widget)))

(defmethod handle-keyboard-event ((widget <check-box>) (ev widget-keyboard-input))
  (when (eq (widget-keyboard-input-key ev) :space)
    (activate-widget widget)))

(defmethod handle-keyboard-event ((widget <entry>) (ev widget-keyboard-input))
  (let* ((key (widget-keyboard-input-key ev))
         (char (widget-keyboard-input-char ev))
         (ctrl (widget-keyboard-input-ctrl ev))
         (shift (widget-keyboard-input-shift ev)))
    (cond
      ((and ctrl (eq key :a))
       (set-<entry>-selection widget 0 (length (<entry>-text widget)))
       t)
      ((and ctrl (eq key :c))
       (<entry>-copy-to-clipboard widget)
       t)
      ((and ctrl (eq key :v))
       (<entry>-paste-from-clipboard widget)
       t)
      ((and ctrl (eq key :x))
       (<entry>-copy-to-clipboard widget)
       (<entry>-delete-selection widget)
       t)
      ((and ctrl shift (eq key :left))
       (<entry>-select-previous-word widget))
      ((and ctrl shift (eq key :right))
       (<entry>-select-next-word widget))
      ((and ctrl shift (eq key :home))
       (<entry>-select-to-start widget))
      ((and ctrl shift (eq key :end))
       (<entry>-select-to-end widget))
      ((and ctrl (eq key :left))
       (<entry>-move-to-previous-word widget)
       t)
      ((and ctrl (eq key :right))
       (<entry>-move-to-next-word widget)
       t)
      ((and shift (eq key :left))
       (<entry>-select-previous-char widget))
      ((and shift (eq key :right))
       (<entry>-select-next-char widget))
      ((and (null key) (characterp char))
       (<entry>-delete-selection widget)
       (let* ((text (<entry>-text widget))
              (new-text (concatenate 'string
                                     (subseq text 0 (<entry>-cursor widget))
                                     (string char)
                                     (subseq text (<entry>-cursor widget)))))
         (when (and (< (length new-text) (<entry>-max-length widget))
                    (<entry>-valid-text-p widget new-text))
           (setf (<entry>-text widget) new-text)
           (incf (<entry>-cursor widget))
           (<entry>-ensure-cursor-visible widget)
           (update-<widget>-value widget new-text)))
       t)
      (t
       (cond
         ((eq key :backspace)
          (unless (<entry>-delete-selection widget)
            (when (> (<entry>-cursor widget) 0)
              (let ((text (<entry>-text widget)))
                (setf (<entry>-text widget)
                      (concatenate 'string
                                   (subseq text 0 (1- (<entry>-cursor widget)))
                                   (subseq text (<entry>-cursor widget))))
                (decf (<entry>-cursor widget))
                (<entry>-ensure-cursor-visible widget)
                (update-<widget>-value widget (<entry>-text widget)))))
          t)
         ((eq key :delete)
          (unless (<entry>-delete-selection widget)
            (when (< (<entry>-cursor widget) (length (<entry>-text widget)))
              (let ((text (<entry>-text widget)))
                (setf (<entry>-text widget)
                      (concatenate 'string
                                   (subseq text 0 (<entry>-cursor widget))
                                   (subseq text (1+ (<entry>-cursor widget)))))
                (<entry>-ensure-cursor-visible widget)
                (update-<widget>-value widget (<entry>-text widget)))))
          t)
         ((eq key :left)
          (when (> (<entry>-cursor widget) 0)
            (decf (<entry>-cursor widget)))
          (clear-<entry>-selection widget)
          (<entry>-ensure-cursor-visible widget)
          t)
         ((eq key :right)
          (when (< (<entry>-cursor widget) (length (<entry>-text widget)))
            (incf (<entry>-cursor widget)))
          (clear-<entry>-selection widget)
          (<entry>-ensure-cursor-visible widget)
          t)
         ((eq key :home)
          (setf (<entry>-cursor widget) 0)
          (clear-<entry>-selection widget)
          (<entry>-scroll-to-start widget)
          t)
         ((eq key :end)
          (setf (<entry>-cursor widget) (length (<entry>-text widget)))
          (clear-<entry>-selection widget)
          (<entry>-scroll-to-end widget)
          t)
         ((member key '(:pageup :pagedown))
          t)
         (t nil))))))

(defmethod handle-keyboard-event ((widget <password-entry>) ev)
  (let ((key (widget-keyboard-input-key (normalize-keyboard-event ev)))
        (ctrl (widget-keyboard-input-ctrl (normalize-keyboard-event ev))))
    (cond
      ((and ctrl (member key '(:c :x) :test #'eq))
       t)
      (t
       (call-next-method)))))

(defmethod handle-keyboard-event ((widget <tree-view>) (ev widget-keyboard-input))
  (let* ((key (widget-keyboard-input-key ev))
         (rows (tree-view-visible-rows widget))
         (selected (<tree-view>-selected-node widget))
         (visible-count (tree-view-visible-row-count widget))
         (current-index (position selected rows :key #'first :test #'eq)))
    (cond
      ((or (eq key :up) (eq key :down))
       (when (and (null current-index) rows)
         (setf current-index 0)
         (<tree-view>-select-node widget (first (first rows))))
       (when current-index
         (let* ((step (if (eq key :up) -1 1))
                (new-index (max 0 (min (1- (length rows)) (+ current-index step)))))
           (<tree-view>-select-node widget (first (nth new-index rows)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((or (eq key :pageup) (eq key :pagedown))
       (when rows
         (let* ((step (if (eq key :pageup) (- visible-count) visible-count))
                (start-index (or current-index 0))
                (new-index (max 0 (min (1- (length rows)) (+ start-index step)))))
           (<tree-view>-select-node widget (first (nth new-index rows)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :left)
       (when selected
         (if (and (tree-node-has-children-p selected)
                  (<tree-node>-expanded-p selected))
             (setf (<tree-node>-expanded-p selected) nil)
             (let ((parent (tree-view-parent-node widget selected)))
               (when parent
                 (<tree-view>-select-node widget parent)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :right)
       (when selected
         (cond
           ((and (tree-node-has-children-p selected)
                 (not (<tree-node>-expanded-p selected)))
            (tree-view-expand-node widget selected))
           ((and (tree-node-has-children-p selected)
                 (<tree-node>-expanded-p selected))
            (when (and (<tree-node>-directory-p selected)
                       (not (<tree-node>-children-loaded-p selected)))
              (tree-view-load-node-children widget selected))
            (<tree-view>-select-node widget (first (<tree-node>-children selected))))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :home)
       (when rows
         (<tree-view>-select-node widget (first (first rows))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :end)
       (when rows
         (<tree-view>-select-node widget (first (car (last rows)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((or (eq key :space) (eq key :return))
       (when (and selected (tree-node-has-children-p selected))
         (tree-view-toggle-node-expanded widget selected))
       (ensure-tree-view-selection-visible widget)
       t)
      (t nil))))

(defmethod handle-keyboard-event ((widget <list-box>) (ev widget-keyboard-input))
  (let* ((key (widget-keyboard-input-key ev))
         (visible-count (<list-box>-visible-item-count widget)))
    (cond
      ((eq key :up)
       (when (> (<list-box>-selected-index widget) 0)
         (decf (<list-box>-selected-index widget))
         (ensure-list-box-selection-visible widget)
         (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                            (<list-box>-items widget))))
       t)
      ((eq key :down)
       (when (< (1+ (<list-box>-selected-index widget))
                (length (<list-box>-items widget)))
         (incf (<list-box>-selected-index widget))
         (ensure-list-box-selection-visible widget)
         (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                            (<list-box>-items widget))))
       t)
      ((eq key :pageup)
       (when (> (<list-box>-selected-index widget) 0)
         (setf (<list-box>-selected-index widget)
               (max 0 (- (<list-box>-selected-index widget) visible-count)))
         (ensure-list-box-selection-visible widget)
         (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                            (<list-box>-items widget))))
       t)
      ((eq key :pagedown)
       (when (plusp (length (<list-box>-items widget)))
         (setf (<list-box>-selected-index widget)
               (min (1- (length (<list-box>-items widget)))
                    (+ (<list-box>-selected-index widget) visible-count)))
         (ensure-list-box-selection-visible widget)
         (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                            (<list-box>-items widget))))
       t)
      (t nil))))

(defmethod handle-keyboard-event ((widget <editable-combo-box>) (ev widget-keyboard-input))
  (let ((key (widget-keyboard-input-key ev)))
    (cond
      ((and (eq key :escape)
            (<combo-box>-expanded-p widget))
       (sync-combo-box-expanded-state widget nil)
       t)
      ((eq key :return)
       (let* ((text (string-trim '(#\Space #\Tab #\Newline #\Return)
                                 (<entry>-text widget))))
         (when (> (length text) 0)
           (combo-box-add-item widget text :select t)
           (setf (<entry>-text widget) text
                 (<entry>-cursor widget) (length text)))
         (sync-combo-box-expanded-state widget nil)
         t))
      ((and (<combo-box>-expanded-p widget)
            (member key '(:up :down :pageup :pagedown)))
       (let ((handled (call-next-method)))
         (when (null handled)
           (setf handled (call-next-method)))
         (when handled
           (let ((item (combo-box-selected-item widget)))
             (when item
               (setf (<entry>-text widget) (format nil "~a" item)
                     (<entry>-cursor widget) (length (<entry>-text widget))
                     (<widget>-value widget) (<entry>-text widget)))))
         t))
      (t
       (call-next-method)))))

(defmethod handle-keyboard-event ((widget <combo-box>) (ev widget-keyboard-input))
  (let* ((key (widget-keyboard-input-key ev))
         (visible-count (combo-box-visible-item-count widget))
         (item-count (length (<list-box>-items widget))))
    (cond
      ((eq key :return)
       (if (<combo-box>-expanded-p widget)
           (progn
             (sync-combo-box-expanded-state widget nil)
             (update-<widget>-value widget (combo-box-selected-item widget))
             t)
           (activate-widget widget)))
      ((eq key :space)
       (activate-widget widget))
      ((eq key :up)
       (when (> (<list-box>-selected-index widget) 0)
         (decf (<list-box>-selected-index widget))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :down)
       (when (< (1+ (<list-box>-selected-index widget)) item-count)
         (incf (<list-box>-selected-index widget))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :pageup)
       (when (> (<list-box>-selected-index widget) 0)
         (setf (<list-box>-selected-index widget)
               (max 0 (- (<list-box>-selected-index widget) visible-count)))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :pagedown)
       (when (plusp item-count)
         (setf (<list-box>-selected-index widget)
               (min (1- item-count)
                    (+ (<list-box>-selected-index widget) visible-count)))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :escape)
       (when (<combo-box>-expanded-p widget)
         (sync-combo-box-expanded-state widget nil))
       t)
      (t nil))))
