;;;; ./src/widgets/methods/handle-widget-key-press.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod handle-widget-key-press :around ((widget <widget>) key char)
  (declare (ignore key char))
  (when (and (enabled-p widget) (visible-p widget))
    (call-next-method)))

(defmethod handle-widget-key-press ((widget <widget>) key char)
  (declare (ignore key char))
  nil)

(defmethod handle-widget-key-press ((widget button) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget toggle) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget check-box) key char)
  (declare (ignore char))
  (when (eq key :space)
    (activate-widget widget)))

(defmethod handle-widget-key-press ((widget entry) key char)
  (cond
    ((eq key :backspace)
     (unless (entry-delete-selection widget)
       (when (> (entry-cursor widget) 0)
         (let ((text (entry-text widget)))
           (setf (entry-text widget)
                 (concatenate 'string
                              (subseq text 0 (1- (entry-cursor widget)))
                              (subseq text (entry-cursor widget))))
           (decf (entry-cursor widget))
           (entry-ensure-cursor-visible widget)
           (update-<widget>-value widget (entry-text widget)))))
     t)
    ((eq key :delete)
     (unless (entry-delete-selection widget)
       (when (< (entry-cursor widget) (length (entry-text widget)))
         (let ((text (entry-text widget)))
           (setf (entry-text widget)
                 (concatenate 'string
                              (subseq text 0 (entry-cursor widget))
                              (subseq text (1+ (entry-cursor widget)))))
           (entry-ensure-cursor-visible widget)
           (update-<widget>-value widget (entry-text widget)))))
     t)
    ((eq key :left)
     (when (> (entry-cursor widget) 0)
       (decf (entry-cursor widget)))
     (clear-entry-selection widget)
     (entry-ensure-cursor-visible widget)
     t)
    ((eq key :right)
     (when (< (entry-cursor widget) (length (entry-text widget)))
       (incf (entry-cursor widget)))
     (clear-entry-selection widget)
     (entry-ensure-cursor-visible widget)
     t)
    ((eq key :home)
     (setf (entry-cursor widget) 0)
     (clear-entry-selection widget)
     (entry-scroll-to-start widget)
     t)
    ((eq key :end)
     (setf (entry-cursor widget) (length (entry-text widget)))
     (clear-entry-selection widget)
     (entry-scroll-to-end widget)
     t)
    ((member key '(:pageup :pagedown))
     t)
    ((characterp char)
     (entry-delete-selection widget)
     (let* ((text (entry-text widget))
            (new-text (concatenate 'string
                                   (subseq text 0 (entry-cursor widget))
                                   (string char)
                                   (subseq text (entry-cursor widget)))))
       (when (and (< (length new-text) (entry-max-length widget))
                  (entry-valid-text-p widget new-text))
         (setf (entry-text widget) new-text)
         (incf (entry-cursor widget))
         (entry-ensure-cursor-visible widget)
         (update-<widget>-value widget new-text)))
     t)
    (t nil)))

(defmethod handle-widget-key-press ((widget tree-view) key char)
  (declare (ignore char))
  (let* ((rows (tree-view-visible-rows widget))
         (selected (tree-view-selected-node widget))
         (visible-count (tree-view-visible-row-count widget))
         (current-index (position selected rows :key #'first :test #'eq)))
    (cond
      ((or (eq key :up) (eq key :down))
       (when (and (null current-index) rows)
         (setf current-index 0)
         (tree-view-select-node widget (first (first rows))))
       (when current-index
         (let* ((step (if (eq key :up) -1 1))
                (new-index (max 0 (min (1- (length rows)) (+ current-index step)))))
           (tree-view-select-node widget (first (nth new-index rows)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((or (eq key :pageup) (eq key :pagedown))
       (when rows
         (let* ((step (if (eq key :pageup) (- visible-count) visible-count))
                (start-index (or current-index 0))
                (new-index (max 0 (min (1- (length rows)) (+ start-index step)))))
           (tree-view-select-node widget (first (nth new-index rows)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :left)
       (when selected
         (if (and (tree-node-has-children-p selected)
                  (tree-node-expanded-p selected))
             (setf (tree-node-expanded-p selected) nil)
             (let ((parent (tree-view-parent-node widget selected)))
               (when parent
                 (tree-view-select-node widget parent)))))
       (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :right)
       (when selected
         (cond
           ((and (tree-node-has-children-p selected)
                 (not (tree-node-expanded-p selected)))
          (tree-view-expand-node widget selected))
           ((and (tree-node-has-children-p selected)
                 (tree-node-expanded-p selected))
          (when (and (tree-node-directory-p selected)
               (not (tree-node-children-loaded-p selected)))
            (tree-view-load-node-children widget selected))
            (tree-view-select-node widget (first (tree-node-children selected))))))
         (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :home)
       (when rows
         (tree-view-select-node widget (first (first rows))))
         (ensure-tree-view-selection-visible widget)
       t)
      ((eq key :end)
       (when rows
         (tree-view-select-node widget (first (car (last rows)))))
         (ensure-tree-view-selection-visible widget)
       t)
      ((or (eq key :space) (eq key :return))
       (when (and selected (tree-node-has-children-p selected))
         (tree-view-toggle-node-expanded widget selected))
         (ensure-tree-view-selection-visible widget)
       t)
      (t nil)))

(defmethod handle-widget-key-press ((widget <list-box>) key char)
  (declare (ignore char))
  (let ((visible-count (<list-box>-visible-item-count widget)))
    (cond
    ((eq key :up)
     (when (> (<list-box>-selected-index widget) 0)
       (decf (<list-box>-selected-index widget))
       (ensure-list-box-selection-visible widget)
       (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                        (<list-box>-items widget))))
     t)
    ((eq key :down)
     (when (< (1+ (<list-box>-selected-index widget))
              (length (<list-box>-items widget)))
       (incf (<list-box>-selected-index widget))
       (ensure-list-box-selection-visible widget)
       (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                        (<list-box>-items widget))))
     t)
    ((eq key :pageup)
     (when (> (<list-box>-selected-index widget) 0)
       (setf (<list-box>-selected-index widget)
             (max 0 (- (<list-box>-selected-index widget) visible-count)))
       (ensure-list-box-selection-visible widget)
       (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                        (<list-box>-items widget))))
     t)
    ((eq key :pagedown)
     (when (plusp (length (<list-box>-items widget)))
       (setf (<list-box>-selected-index widget)
             (min (1- (length (<list-box>-items widget)))
                  (+ (<list-box>-selected-index widget) visible-count)))
       (ensure-list-box-selection-visible widget)
       (update-<widget>-value widget (nth (<list-box>-selected-index widget)
                                        (<list-box>-items widget))))
     t)
    (t nil))))

(defmethod handle-widget-key-press ((widget editable-combo-box) key char)
  (declare (ignore char))
  (cond
    ((and (eq key :escape)
          (<combo-box>-expanded-p widget))
     (sync-combo-box-expanded-state widget nil)
     t)
    ((eq key :return)
     (let* ((text (string-trim '(#\Space #\Tab #\Newline #\Return)
                               (entry-text widget))))
       (when (> (length text) 0)
         (combo-box-add-item widget text :select t)
         (setf (entry-text widget) text
               (entry-cursor widget) (length text)))
       (sync-combo-box-expanded-state widget nil)
       t))
    ((and (<combo-box>-expanded-p widget)
          (member key '(:up :down :pageup :pagedown)))
     (let ((handled (call-next-method)))
       (when (null handled)
         (setf handled (call-next-method)))
       (when handled
         (let ((item (combo-box-selected-item widget)))
           (when item
             (setf (entry-text widget) (format nil "~a" item)
                   (entry-cursor widget) (length (entry-text widget))
                   (<widget>-value widget) (entry-text widget)))))
       t))
    (t
     (call-next-method))))

(defmethod handle-widget-key-press ((widget combo-box) key char)
  (declare (ignore char))
  (let ((visible-count (combo-box-visible-item-count widget))
        (item-count (length (<list-box>-items widget))))
    (cond
      ((eq key :return)
       (if (<combo-box>-expanded-p widget)
           (progn
             (sync-combo-box-expanded-state widget nil)
             (update-<widget>-value widget (combo-box-selected-item widget))
             t)
           (activate-widget widget)))
      ((eq key :space)
       (activate-widget widget))
      ((eq key :up)
       (when (> (<list-box>-selected-index widget) 0)
         (decf (<list-box>-selected-index widget))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :down)
       (when (< (1+ (<list-box>-selected-index widget)) item-count)
         (incf (<list-box>-selected-index widget))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :pageup)
       (when (> (<list-box>-selected-index widget) 0)
         (setf (<list-box>-selected-index widget)
               (max 0 (- (<list-box>-selected-index widget) visible-count)))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :pagedown)
       (when (plusp item-count)
         (setf (<list-box>-selected-index widget)
               (min (1- item-count)
                    (+ (<list-box>-selected-index widget) visible-count)))
         (ensure-combo-box-selection-visible widget)
         (update-<widget>-value widget (combo-box-selected-item widget)))
       t)
      ((eq key :escape)
       (when (<combo-box>-expanded-p widget)
         (sync-combo-box-expanded-state widget nil))
       t)
      (t nil)))))
