;;;; ./src/widgets/methods/handle-widget-key-event.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod handle-widget-key-event :around ((widget widget) key char &key ctrl shift alt)
  (declare (ignore key char ctrl shift alt))
  (when (and (widget-enabled widget) (widget-visible widget))
    (call-next-method)))

(defmethod handle-widget-key-event ((widget widget) key char &key ctrl shift alt)
  (declare (ignore ctrl shift alt))
  (handle-widget-key-press widget key char))

(defmethod handle-widget-key-event ((widget entry) key char &key ctrl shift alt)
  (declare (ignore alt))
  (cond
    ((and ctrl (eq key :a))
     (set-entry-selection widget 0 (length (entry-text widget)))
     t)
    ((and ctrl (eq key :c))
     (entry-copy-to-clipboard widget)
     t)
    ((and ctrl (eq key :v))
     (entry-paste-from-clipboard widget)
     t)
    ((and ctrl (eq key :x))
     (entry-copy-to-clipboard widget)
     (entry-delete-selection widget)
     t)
    ((and ctrl shift (eq key :left))
     (entry-select-previous-word widget))
    ((and ctrl shift (eq key :right))
     (entry-select-next-word widget))
    ((and ctrl shift (eq key :home))
     (entry-select-to-start widget))
    ((and ctrl shift (eq key :end))
     (entry-select-to-end widget))
    ((and ctrl (eq key :left))
     (entry-move-to-previous-word widget)
     t)
    ((and ctrl (eq key :right))
     (entry-move-to-next-word widget)
     t)
    ((and shift (eq key :left))
     (entry-select-previous-char widget))
    ((and shift (eq key :right))
     (entry-select-next-char widget))
    (t
     (handle-widget-key-press widget key char))))