;;;; ./src/widgets/methods/render-widget-with-style.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod render-widget-with-style ((style widget-style) renderer (widget label))
  (declare (ignore style))
  (render renderer widget))

(defmethod render-widget-with-style ((style widget-style) renderer (widget toggle))
  (declare (ignore style))
  (render renderer widget))

(defmethod render-widget-with-style ((style widget-style) renderer (widget check-box))
  (declare (ignore style))
  (render renderer widget))

(defmethod render-widget-with-style ((style widget-style) renderer (widget edit-box))
  (declare (ignore style))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             (if (widget-focused widget) '(255 255 255 255) '(245 245 245 255)))
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               (if (widget-focused widget) +color-focus-border+ +color-border+)
               2)
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render-widget-with-style ((style flat-widget-style) renderer (widget edit-box))
  (call-next-method))

(defmethod render-widget-with-style ((style windows-widget-style) renderer (widget edit-box))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget)))
    (fill-rect renderer x y w h '(255 255 255 255))
    (render-bevel-rect renderer x y w h '(128 128 128 255) '(255 255 255 255) 1)
    (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                       '(64 64 64 255) '(224 224 224 255) 1)
    (when (widget-focused widget)
      (stroke-rect renderer (+ x 2) (+ y 2) (- w 4) (- h 4) +color-focus-border+ 1)))
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render-widget-with-style ((style motif-widget-style) renderer (widget edit-box))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget)))
    (fill-rect renderer x y w h '(250 250 250 255))
    (render-bevel-rect renderer x y w h '(110 110 110 255) '(238 238 238 255) 2)
    (when (widget-focused widget)
      (stroke-rect renderer (+ x 3) (+ y 3) (- w 6) (- h 6) +color-focus-border+ 1)))
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render-widget-with-style ((style widget-style) renderer (widget list-box))
  (declare (ignore style))
  (render renderer widget))

(defmethod render-widget-with-style ((style flat-widget-style) renderer (widget button))
  (let ((color (cond
                 ((not (widget-enabled widget)) +color-disabled+)
                 ((button-pressed-p widget) +color-button-active+)
                 (t +color-bg+))))
    (fill-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               color)
    (stroke-rect renderer (widget-x widget) (widget-y widget)
                 (widget-width widget) (widget-height widget)
                 +color-border+
                 2)
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-y (if (button-pressed-p widget) 1 0)))

(defmethod render-widget-with-style ((style windows-widget-style) renderer (widget button))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget))
        (pressed (button-pressed-p widget))
        (face (if (widget-enabled widget) '(212 208 200 255) '(190 190 190 255))))
    (fill-rect renderer x y w h face)
    (if pressed
        (progn
          (render-bevel-rect renderer x y w h '(128 128 128 255) '(255 255 255 255) 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             '(64 64 64 255) '(240 240 240 255) 1))
        (progn
          (render-bevel-rect renderer x y w h '(255 255 255 255) '(128 128 128 255) 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             '(240 240 240 255) '(64 64 64 255) 1)))
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget :inset 2)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-x (if (button-pressed-p widget) 1 0)
                       :offset-y (if (button-pressed-p widget) 1 0)))

(defmethod render-widget-with-style ((style motif-widget-style) renderer (widget button))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget))
        (pressed (button-pressed-p widget))
        (face (if (widget-enabled widget) '(196 196 196 255) '(170 170 170 255))))
    (fill-rect renderer x y w h face)
    (if pressed
        (render-bevel-rect renderer x y w h '(90 90 90 255) '(238 238 238 255) 2)
        (render-bevel-rect renderer x y w h '(238 238 238 255) '(90 90 90 255) 2))
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget :inset 4)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-x (if (button-pressed-p widget) 1 0)
                       :offset-y (if (button-pressed-p widget) 1 0)))