;;;; ./src/widgets/methods/render.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod render (renderer (widget label) style)
  (declare (ignore style))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             +color-bg+)
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               +color-border+)
  (render-text renderer (label-text widget)
               (+ (widget-x widget) +widget-padding+)
               (+ (widget-y widget) +widget-padding+)
               (if (widget-enabled widget) +color-text+ +color-disabled+)))

(defmethod render (renderer (widget button) (style widget-style))
  (declare (ignore style))
  (let ((color (cond
                 ((not (widget-enabled widget)) +color-disabled+)
                 ((button-pressed-p widget) +color-button-active+)
                 (t +color-bg+))))
    (fill-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               color)
    (stroke-rect renderer (widget-x widget) (widget-y widget)
                 (widget-width widget) (widget-height widget)
                 +color-border+
                 2)
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-y (if (button-pressed-p widget) 1 0)))

(defmethod render (renderer (widget toggle) style)
  (declare (ignore style))
  (let* ((circle-radius 8)
         (indicator-width (* 2 circle-radius))
         (toggle-height 20)
         (toggle-x (widget-x widget))
         (toggle-y (+ (widget-y widget) (/ (- (widget-height widget) toggle-height) 2)))
         (circle-cx (+ toggle-x circle-radius))
         (circle-cy (+ toggle-y circle-radius))
         (label-height (nth-value 1 (widget-text-pixel-size (toggle-label widget))))
         (label-gap (nth-value 0 (widget-text-pixel-size "M")))
         (label-x (+ toggle-x indicator-width label-gap))
         (label-y (+ toggle-y (/ (- indicator-width label-height) 2))))
    (fill-circle renderer circle-cx circle-cy circle-radius +color-bg+)
    (stroke-circle renderer circle-cx circle-cy circle-radius +color-border+)
    (when (toggle-state widget)
      (fill-circle renderer circle-cx circle-cy 4 +color-text+))
    (when (widget-focused widget)
      (stroke-rect renderer (widget-x widget) (widget-y widget)
                   (widget-width widget) (widget-height widget)
                   +color-focus-border+ 1))
    (render-text renderer (toggle-label widget) label-x label-y +color-text+)))

(defmethod render (renderer (widget check-box) style)
  (declare (ignore style))
  (let* ((box-size 16)
         (box-x (widget-x widget))
         (box-y (+ (widget-y widget) (/ (- (widget-height widget) box-size) 2)))
         (label-height (nth-value 1 (widget-text-pixel-size (check-box-label widget))))
         (label-gap (nth-value 0 (widget-text-pixel-size "M"))))
    (fill-rect renderer box-x box-y box-size box-size +color-bg+)
    (stroke-rect renderer box-x box-y box-size box-size +color-border+)
    (when (check-box-checked widget)
      (fill-rect renderer (+ box-x 3) (+ box-y 3) 10 10 +color-text+))
    (when (widget-focused widget)
      (stroke-rect renderer (widget-x widget) (widget-y widget)
                   (widget-width widget) (widget-height widget)
                   +color-focus-border+ 1))
    (render-text renderer (check-box-label widget)
                 (+ box-x box-size label-gap)
                 (+ box-y (/ (- box-size label-height) 2))
                 +color-text+)))

(defmethod render (renderer (widget edit-box) (style widget-style))
  (declare (ignore style))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             (if (widget-focused widget) '(255 255 255 255) '(245 245 245 255)))
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               (if (widget-focused widget) +color-focus-border+ +color-border+)
               2)
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render (renderer (widget edit-box) (style windows-widget-style))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget)))
    (fill-rect renderer x y w h '(255 255 255 255))
    (render-bevel-rect renderer x y w h '(128 128 128 255) '(255 255 255 255) 1)
    (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                       '(64 64 64 255) '(224 224 224 255) 1)
    (when (widget-focused widget)
      (stroke-rect renderer (+ x 2) (+ y 2) (- w 4) (- h 4) +color-focus-border+ 1)))
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render (renderer (widget edit-box) (style motif-widget-style))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget)))
    (fill-rect renderer x y w h '(250 250 250 255))
    (render-bevel-rect renderer x y w h '(110 110 110 255) '(238 238 238 255) 2)
    (when (widget-focused widget)
      (stroke-rect renderer (+ x 3) (+ y 3) (- w 6) (- h 6) +color-focus-border+ 1)))
  (render-edit-box-text-and-cursor renderer widget))

(defmethod render (renderer (widget list-box) style)
  (declare (ignore style))
  (normalize-list-box-scroll-offset widget)
  (let* ((scrollbar-width +list-box-scrollbar-width+)
         (visible-count (list-box-visible-item-count widget))
         (item-count (length (list-box-items widget)))
         (scrollbar-needed-p (list-box-scrollbar-needed-p widget))
         (content-width (list-box-content-width widget))
         (scroll-offset (list-box-scroll-offset widget)))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             +color-bg+)
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               +color-border+)
  (loop for i from scroll-offset below (min item-count (+ scroll-offset visible-count))
        for item in (nthcdr scroll-offset (list-box-items widget))
        for row from 0
        for item-y = (+ (widget-y widget) (* row (list-box-item-height widget)))
        do (progn
             (when (= i (list-box-selected-index widget))
               (fill-rect renderer (widget-x widget) item-y
                          content-width (list-box-item-height widget)
                          +color-highlight+))
             (render-text renderer (format nil "~a" item)
                          (+ (widget-x widget) +widget-padding+)
                          (+ item-y (/ (- (list-box-item-height widget) +font-text-height+) 2))
                          +color-text+)))
  (when scrollbar-needed-p
    (multiple-value-bind (needed-p track-x track-y track-height thumb-y thumb-height max-offset)
        (list-box-scrollbar-geometry widget)
      (declare (ignore needed-p max-offset))
      (fill-rect renderer track-x track-y scrollbar-width track-height '(232 232 232 255))
      (stroke-rect renderer track-x track-y scrollbar-width track-height '(180 180 180 255))
      (fill-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height '(180 180 180 255))
      (stroke-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height '(120 120 120 255))))))

(defmethod render (renderer (widget button) (style windows-widget-style))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget))
        (pressed (button-pressed-p widget))
        (face (if (widget-enabled widget) '(212 208 200 255) '(190 190 190 255))))
    (fill-rect renderer x y w h face)
    (if pressed
        (progn
          (render-bevel-rect renderer x y w h '(128 128 128 255) '(255 255 255 255) 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             '(64 64 64 255) '(240 240 240 255) 1))
        (progn
          (render-bevel-rect renderer x y w h '(255 255 255 255) '(128 128 128 255) 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             '(240 240 240 255) '(64 64 64 255) 1)))
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget :inset 2)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-x (if (button-pressed-p widget) 1 0)
                       :offset-y (if (button-pressed-p widget) 1 0)))

(defmethod render (renderer (widget button) (style motif-widget-style))
  (declare (ignore style))
  (let ((x (widget-x widget))
        (y (widget-y widget))
        (w (widget-width widget))
        (h (widget-height widget))
        (pressed (button-pressed-p widget))
        (face (if (widget-enabled widget) '(196 196 196 255) '(170 170 170 255))))
    (fill-rect renderer x y w h face)
    (if pressed
        (render-bevel-rect renderer x y w h '(90 90 90 255) '(238 238 238 255) 2)
        (render-bevel-rect renderer x y w h '(238 238 238 255) '(90 90 90 255) 2))
    (when (widget-focused widget)
      (render-button-focus-outline renderer widget :inset 4)))
  (render-button-label renderer widget
                       (if (widget-enabled widget) +color-text+ +color-disabled+)
                       :offset-x (if (button-pressed-p widget) 1 0)
                       :offset-y (if (button-pressed-p widget) 1 0)))