;;;; ./src/widgets/methods/render.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod render :around (renderer (widget <widget>) style)
  (declare (ignore style))
  (when (visible-p widget)
    (call-next-method)))

(defmethod render (renderer (widget <label>) style)
  (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
             (<widget>-width widget) (<widget>-height widget)
             (<widget-style>-background-color style))
  (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) (<widget>-height widget)
               (<widget-style>-border-color style))
  (let ((text-padding (<widget-style>-text-padding style)))
    (render-text renderer (<label>-text widget)
                 (+ (<widget>-x widget) text-padding)
                 (+ (<widget>-y widget) text-padding)
                 (if (enabled-p widget)
                     (<widget-style>-text-color style)
                     (<widget-style>-disabled-color style)))))

(defmethod render (renderer (widget <widget-container>) style)
  (declare (ignore style))
  (dolist (child (children widget))
    (render renderer child style)))

(defmethod render (renderer (widget <scroll-container>) style)
  (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
             (<widget>-width widget) (<widget>-height widget)
             (<widget-style>-background-color style))
  (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) (<widget>-height widget)
               (<widget-style>-border-color style))
  (dolist (child (children widget))
    (render renderer child style)))

(defmethod render (renderer (widget <split-pane>) style)
  (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
             (<widget>-width widget) (<widget>-height widget)
             (<widget-style>-background-color style))
  (let* ((padding (<split-pane>-padding widget))
         (orientation (<split-pane>-orientation widget))
         (divider-size (max 0 (<split-pane>-divider-size widget)))
         (inner-x (+ (<widget>-x widget) padding))
         (inner-y (+ (<widget>-y widget) padding))
         (inner-w (max 1 (- (<widget>-width widget) (* 2 padding))))
         (inner-h (max 1 (- (<widget>-height widget) (* 2 padding))))
         (ratio (max 0 (min 1 (<split-pane>-ratio widget))))
         (split-pos (if (eq orientation :vertical)
                        (max 0 (round (* ratio (- inner-h divider-size))))
                        (max 0 (round (* ratio (- inner-w divider-size))))))
         (divider-x (if (eq orientation :horizontal)
                        (+ inner-x split-pos)
                        inner-x))
         (divider-y (if (eq orientation :vertical)
                        (+ inner-y split-pos)
                        inner-y))
         (divider-w (if (eq orientation :horizontal)
                        divider-size
                        inner-w))
         (divider-h (if (eq orientation :vertical)
                        divider-size
                        inner-h)))
    (fill-rect renderer divider-x divider-y divider-w divider-h (<widget-style>-border-color style))
    (dolist (child (children widget))
      (render renderer child style))))

(defmethod render (renderer (widget <toolbar>) style)
    (let* ((x (<widget>-x widget))
      (y (<widget>-y widget))
      (chs (children widget))
      (pad (or (<toolbar>-padding widget) (<widget-style>-toolbar-padding style)))
      (spacing (<widget-style>-toolbar-spacing style))
      (w (if (and chs (plusp (length chs)))
        (+ (reduce #'+ (mapcar #'<widget>-width chs) :initial-value 0)
           (* 2 pad)
           (* spacing (max 0 (1- (length chs)))))
        (<widget>-width widget)))
     (h (if (and chs (plusp (length chs)))
       (reduce #'max (mapcar #'<widget>-height chs) :initial-value 0)
       (<widget>-height widget)))
     (bg (<toolbar>-background widget)))
    (when bg
      (fill-rect renderer x y w h bg))
    (stroke-rect renderer x y w h (<widget-style>-border-color style))
    (let ((cx (+ x pad)))
      (dolist (child chs)
        (when (visible-p child)
          (let ((cw (max 1 (<widget>-width child)))
                (ch (max 1 (<widget>-height child))))
            (place-widget child :x cx :y (+ y (floor (/ (- h ch) 2))) :width cw :height ch)
            (render renderer child style)
            (incf cx (+ cw spacing))))))))

(defmethod render (renderer (widget <toolbar-button>) style)
    (when (visible-p widget)
      (let* ((x (<widget>-x widget))
             (y (<widget>-y widget))
             (w (<widget>-width widget))
             (h (<widget>-height widget))
             (<label> (or (<toolbar-button>-label widget) ""))
             (txt-color (if (enabled-p widget)
                            (<widget-style>-text-color style)
                            (<widget-style>-disabled-color style)))
             (bg-color (if (and (eql :toggle (<toolbar-button>-type widget))
                               (<toolbar-button>-checked-p widget))
                           (<widget-style>-toolbar-toggle-active-color style)
                           (<widget-style>-background-color style)))
             (border-color (if (and (eql :toggle (<toolbar-button>-type widget))
                                    (<toolbar-button>-checked-p widget))
                               (<widget-style>-focus-border-color style)
                               (<widget-style>-border-color style)))
             (focus-outline-offset (<widget-style>-focus-outline-offset style))
             (focus-outline-width (max 1 (- w (* 2 focus-outline-offset))))
             (focus-outline-height (max 1 (- h (* 2 focus-outline-offset)))))
        (fill-rect renderer x y w h bg-color)
        (stroke-rect renderer x y w h border-color)
        (when (<widget>-focused widget)
          (stroke-rect renderer
                       (+ x focus-outline-offset)
                       (+ y focus-outline-offset)
                       focus-outline-width
                       focus-outline-height
                       (<widget-style>-focus-border-color style)
                       1))
        (multiple-value-bind (tw th) (text-pixel-size <label>)
          (let ((tx (+ x (floor (/ (- w tw) 2))))
                (ty (+ y (floor (/ (- h th) 2)))))
            (render-text renderer <label> tx ty txt-color))))))

(defun render-toolbar (toolbar renderer x y)
  "Convenience helper: place `toolbar` at X/Y then render it with current style."
  (place-widget toolbar :x (round x) :y (round y))
  (render renderer toolbar mnas-sdl3-gui/widgets:*widget-style*)
  toolbar)

(defun toolbar-buttons-at-position (toolbar x y)
  "Return the toolbar child button at local coordinates X/Y, or NIL."
  (when (and (typep toolbar '<toolbar>)
             (children toolbar))
    (loop for child in (children toolbar)
          when (and (typep child '<toolbar-button>)
                    (<= (or (<widget>-x child) 0) x (+ (or (<widget>-x child) 0) (max 1 (or (<widget>-width child) 0))))
                    (<= (or (<widget>-y child) 0) y (+ (or (<widget>-y child) 0) (max 1 (or (<widget>-height child) 0)))))
            return child)))

(defun toolbar-button-clicked (toolbar button &optional context)
  "Execute the command associated with BUTTON, optionally using CONTEXT."
  (declare (ignore toolbar))
  (when (and (typep button '<toolbar-button>))
    (let ((cmd-id (<toolbar-button>-command-id button)))
      (when cmd-id
        (handler-case
            (mnas-sdl3-gui/commands:execute-command cmd-id :context (or context button))
          (error (e)
            (format *error-output* "Error executing toolbar command ~S: ~S~%" cmd-id e)))))
    button))

(defun update-toolbar-command-state (toolbar)
  "Synchronize toolbar button state from registered commands."
  (when (and (typep toolbar '<toolbar>) (children toolbar))
    (dolist (child (children toolbar))
      (when (typep child '<toolbar-button>)
        (let ((cmd-id (<toolbar-button>-command-id child)))
          (when cmd-id
            (let ((cmd (mnas-sdl3-gui/commands:find-command cmd-id)))
              (when cmd
                (setf (<toolbar-button>-checked-p child)
                      (mnas-sdl3-gui/commands:command-checked cmd))
                (setf (<widget>-visible child)
                      (mnas-sdl3-gui/commands:command-visible cmd))))))))
    toolbar))

(defun register-toolbar-for-command-updates (toolbar)
  "Register TOOLBAR as a command-state consumer for future updates."
  (declare (ignore toolbar))
  nil)

(defmethod render (renderer (widget canvas-2d-widget) style)
  (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
             (<widget>-width widget) (<widget>-height widget)
             (<widget-style>-background-color style))
  (render-canvas-2d-grid renderer widget)
  (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) (<widget>-height widget)
               (<widget-style>-border-color style))
  (if (canvas-2d-widget-scene widget)
      (render-canvas-2d-scene renderer widget)
      (render-canvas-2d-placeholder renderer widget))
  (setf (canvas-2d-widget-redraw-requested widget) nil))

(defmethod render (renderer (obj <button>) (style <widget-style>))
  (let* ((color
          (cond
            ((not (enabled-p obj)) (<widget-style>-disabled-color style))
            ((<button>-pressed-p obj) (<widget-style>-button-active-color style))
            (t (<widget-style>-background-color style))))
         (border-width (<widget-style>-border-width style))
         (label-offset-y (if (<button>-pressed-p obj)
                             (<widget-style>-button-pressed-label-offset style)
                             0)))
    (fill-rect renderer (<widget>-x obj) (<widget>-y obj)
               (<widget>-width obj) (<widget>-height obj)
               color)
    (stroke-rect renderer (<widget>-x obj) (<widget>-y obj)
                 (<widget>-width obj) (<widget>-height obj)
                 (<widget-style>-border-color style)
                 border-width)
    (when (<widget>-focused obj)
      (render-button-focus-outline renderer obj)))
  (render-button-label renderer obj
                       (if (enabled-p obj)
                           (<widget-style>-text-color style)
                           (<widget-style>-disabled-color style))
                       :offset-y label-offset-y))

(defmethod render (renderer (widget <toggle>) style)
  (let* ((circle-radius (<widget-style>-toggle-circle-radius style))
         (indicator-width (* 2 circle-radius))
         (toggle-height (<widget-style>-toggle-height style))
         (indicator-inner-radius (<widget-style>-toggle-indicator-inner-radius style))
         (<toggle>-x (<widget>-x widget))
         (<toggle>-y (+ (<widget>-y widget) (/ (- (<widget>-height widget) toggle-height) 2)))
         (circle-cx (+ <toggle>-x circle-radius))
         (circle-cy (+ <toggle>-y circle-radius))
         (<label>-height (nth-value 1 (widget-text-pixel-size (<toggle>-label widget))))
         (<label>-gap (nth-value 0 (widget-text-pixel-size "M")))
         (<label>-x (+ <toggle>-x indicator-width <label>-gap))
         (<label>-y (+ <toggle>-y (/ (- indicator-width <label>-height) 2))))
    (fill-circle renderer circle-cx circle-cy circle-radius (<widget-style>-background-color style))
    (stroke-circle renderer circle-cx circle-cy circle-radius (<widget-style>-border-color style))
    (when (<toggle>-state widget)
      (fill-circle renderer circle-cx circle-cy indicator-inner-radius (<widget-style>-text-color style)))
    (when (<widget>-focused widget)
      (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                   (<widget>-width widget) (<widget>-height widget)
                   (<widget-style>-focus-border-color style) 1))
    (render-text renderer (<toggle>-label widget) <label>-x <label>-y (<widget-style>-text-color style))))

(defmethod render (renderer (widget <check-box>) style)
  (let* ((box-size (<widget-style>-check-box-size style))
         (box-x (<widget>-x widget))
         (box-y (+ (<widget>-y widget) (/ (- (<widget>-height widget) box-size) 2)))
         (check-mark-offset (<widget-style>-check-mark-offset style))
         (check-mark-size (<widget-style>-check-mark-size style))
         (<label>-height (nth-value 1 (widget-text-pixel-size (<check-box>-label widget))))
         (<label>-gap (nth-value 0 (widget-text-pixel-size "M"))))
    (fill-rect renderer box-x box-y box-size box-size (<widget-style>-background-color style))
    (stroke-rect renderer box-x box-y box-size box-size (<widget-style>-border-color style))
    (when (<check-box>-checked widget)
      (fill-rect renderer (+ box-x check-mark-offset) (+ box-y check-mark-offset)
                 check-mark-size check-mark-size (<widget-style>-text-color style)))
    (when (<widget>-focused widget)
      (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                   (<widget>-width widget) (<widget>-height widget)
                   (<widget-style>-focus-border-color style) 1))
    (render-text renderer (<check-box>-label widget)
                 (+ box-x box-size <label>-gap)
                 (+ box-y (/ (- box-size <label>-height) 2))
                 (<widget-style>-text-color style))))

(defmethod render (renderer (widget <entry>) (style <widget-style>))
  (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
             (<widget>-width widget) (<widget>-height widget)
             (if (<widget>-focused widget)
                 (<widget-style>-panel-background-color style)
                 (<widget-style>-background-color style)))
  (let* ((border-color (if (<widget>-focused widget)
                           (<widget-style>-focus-border-color style)
                           (<widget-style>-border-color style)))
         (border-width (<widget-style>-border-width style)))
    (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                 (<widget>-width widget) (<widget>-height widget)
                 border-color
                 border-width))
  (let* ((text (<entry>-text widget))
         (display-text (or (<entry>-show-text widget) text))
         (text-x (+ (<widget>-x widget) (<widget-style>-text-padding style)))
         (text-y (+ (<widget>-y widget)
                    (/ (- (<widget>-height widget) +font-text-height+) 2)))
         (sel-start (<entry>-selection-start widget))
         (sel-end (<entry>-selection-end widget))
         (has-selection (and (not (null sel-start))
                             (not (null sel-end))
                             (< sel-start sel-end))))
    (multiple-value-bind (visible-start visible-end)
        (<entry>-visible-range widget)
      (labels ((segment-x (position)
                 (+ text-x
                    (compute-text-segment-pixel-width widget visible-start position)))
               (render-visible-segment (start end color)
                 (when (< start end)
                   (render-text renderer (subseq display-text start end)
                                (segment-x start)
                                text-y
                                color))))
        (if has-selection
            (let ((before-start visible-start)
                  (before-end (min visible-end sel-start))
                  (selected-start (max visible-start sel-start))
                  (selected-end (min visible-end sel-end))
                  (after-start (max visible-start sel-end))
                  (after-end visible-end))
              (render-visible-segment before-start before-end (<widget-style>-text-color style))
              (when (< selected-start selected-end)
                (let ((selection-x (segment-x selected-start))
                      (selection-w (compute-text-segment-pixel-width
                                    widget
                                    selected-start
                                    selected-end)))
                  (fill-rect renderer selection-x (- text-y (<widget-style>-selection-padding style))
                             selection-w (+ +font-text-height+ (* 2 (<widget-style>-selection-padding style)))
                             (<widget-style>-selection-background-color style))
                  (render-visible-segment selected-start selected-end
                                          (<widget-style>-selection-text-color style))))
              (render-visible-segment after-start after-end (<widget-style>-text-color style)))
            (progn
              (render-visible-segment visible-start visible-end (<widget-style>-text-color style))
              (when (<widget>-focused widget)
                (let ((cursor-x (segment-x (<entry>-cursor widget))))
                  (sdl3:set-render-draw-color renderer 0 0 0 255)
                  (sdl3:render-line renderer
                                    (float cursor-x 1.0)
                                    (float (+ (<widget>-y widget) (<widget-style>-cursor-offset style)) 1.0)
                                    (float cursor-x 1.0)
                                    (float (- (+ (<widget>-y widget)
                                                 (<widget>-height widget))
                                              (<widget-style>-cursor-offset style))
                                           1.0))))))))))

(defmethod render (renderer (widget <entry>) (style <windows-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (<widget>-height widget)))
    (fill-rect renderer x y w h +color-white+)
    (render-bevel-rect renderer x y w h +color-dark-gray+ +color-white+ 1)
    (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                       +color-darker-gray+ +color-medium-gray+ 1)
    (when (<widget>-focused widget)
      (stroke-rect renderer (+ x 2) (+ y 2) (- w 4) (- h 4) +color-focus-border+ 1)))
  (let* ((text (<entry>-text widget))
         (display-text (or (<entry>-show-text widget) text))
         (text-x (+ (<widget>-x widget) (<widget-style>-text-padding style)))
         (text-y (+ (<widget>-y widget)
                    (/ (- (<widget>-height widget) +font-text-height+) 2)))
         (sel-start (<entry>-selection-start widget))
         (sel-end (<entry>-selection-end widget))
         (has-selection (and (not (null sel-start))
                             (not (null sel-end))
                             (< sel-start sel-end))))
    (multiple-value-bind (visible-start visible-end)
        (<entry>-visible-range widget)
      (labels ((segment-x (position)
                 (+ text-x
                    (compute-text-segment-pixel-width widget visible-start position)))
               (render-visible-segment (start end color)
                 (when (< start end)
                   (render-text renderer (subseq display-text start end)
                                (segment-x start)
                                text-y
                                color))))
        (if has-selection
            (let ((before-start visible-start)
                  (before-end (min visible-end sel-start))
                  (selected-start (max visible-start sel-start))
                  (selected-end (min visible-end sel-end))
                  (after-start (max visible-start sel-end))
                  (after-end visible-end))
              (render-visible-segment before-start before-end (<widget-style>-text-color style))
              (when (< selected-start selected-end)
                (let ((selection-x (segment-x selected-start))
                      (selection-w (compute-text-segment-pixel-width
                                    widget
                                    selected-start
                                    selected-end)))
                  (fill-rect renderer selection-x (- text-y (<widget-style>-selection-padding style))
                             selection-w (+ +font-text-height+ (* 2 (<widget-style>-selection-padding style)))
                             (<widget-style>-selection-background-color style))
                  (render-visible-segment selected-start selected-end
                                          (<widget-style>-selection-text-color style))))
              (render-visible-segment after-start after-end (<widget-style>-text-color style)))
            (progn
              (render-visible-segment visible-start visible-end (<widget-style>-text-color style))
              (when (<widget>-focused widget)
                (let ((cursor-x (segment-x (<entry>-cursor widget))))
                  (sdl3:set-render-draw-color renderer 0 0 0 255)
                  (sdl3:render-line renderer
                                    (float cursor-x 1.0)
                                    (float (+ (<widget>-y widget) (<widget-style>-cursor-offset style)) 1.0)
                                    (float cursor-x 1.0)
                                    (float (- (+ (<widget>-y widget)
                                                 (<widget>-height widget))
                                              (<widget-style>-cursor-offset style))
                                           1.0))))))))))
    

(defmethod render (renderer (widget <entry>) (style <motif-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (<widget>-height widget)))
    (fill-rect renderer x y w h +color-motif-panel-bg+)
    (render-bevel-rect renderer x y w h +color-motif-border+ +color-motif-light+ 2)
    (when (<widget>-focused widget)
      (stroke-rect renderer (+ x 3) (+ y 3) (- w 6) (- h 6) +color-focus-border+ 1)))
  (let* ((text (<entry>-text widget))
         (display-text (or (<entry>-show-text widget) text))
         (text-x (+ (<widget>-x widget) (<widget-style>-text-padding style)))
         (text-y (+ (<widget>-y widget)
                    (/ (- (<widget>-height widget) +font-text-height+) 2)))
         (sel-start (<entry>-selection-start widget))
         (sel-end (<entry>-selection-end widget))
         (has-selection (and (not (null sel-start))
                             (not (null sel-end))
                             (< sel-start sel-end))))
    (multiple-value-bind (visible-start visible-end)
        (<entry>-visible-range widget)
      (labels ((segment-x (position)
                 (+ text-x
                    (compute-text-segment-pixel-width widget visible-start position)))
               (render-visible-segment (start end color)
                 (when (< start end)
                   (render-text renderer (subseq display-text start end)
                                (segment-x start)
                                text-y
                                color))))
        (if has-selection
            (let ((before-start visible-start)
                  (before-end (min visible-end sel-start))
                  (selected-start (max visible-start sel-start))
                  (selected-end (min visible-end sel-end))
                  (after-start (max visible-start sel-end))
                  (after-end visible-end))
              (render-visible-segment before-start before-end (<widget-style>-text-color style))
              (when (< selected-start selected-end)
                (let ((selection-x (segment-x selected-start))
                      (selection-w (compute-text-segment-pixel-width
                                    widget
                                    selected-start
                                    selected-end)))
                  (fill-rect renderer selection-x (- text-y (<widget-style>-selection-padding style))
                             selection-w (+ +font-text-height+ (* 2 (<widget-style>-selection-padding style)))
                             (<widget-style>-selection-background-color style))
                  (render-visible-segment selected-start selected-end
                                          (<widget-style>-selection-text-color style))))
              (render-visible-segment after-start after-end (<widget-style>-text-color style)))
            (progn
              (render-visible-segment visible-start visible-end (<widget-style>-text-color style))
              (when (<widget>-focused widget)
                (let ((cursor-x (segment-x (<entry>-cursor widget))))
                  (sdl3:set-render-draw-color renderer 0 0 0 255)
                  (sdl3:render-line renderer
                                    (float cursor-x 1.0)
                                    (float (+ (<widget>-y widget) (<widget-style>-cursor-offset style)) 1.0)
                                    (float cursor-x 1.0)
                                    (float (- (+ (<widget>-y widget)
                                                 (<widget>-height widget))
                                              (<widget-style>-cursor-offset style))
                                           1.0))))))))))

(defmethod render (renderer (widget <tree-view>) (style <widget-style>))
  (let* ((x (<widget>-x widget))
         (y (<widget>-y widget))
         (w (<widget>-width widget))
         (h (<widget>-height widget))
         (row-height (max 16 (<tree-view>-row-height widget)))
         (indent (max 8 (<tree-view>-indent-width widget)))
         (rows (tree-view-visible-rows widget))
         (scroll-offset (<tree-view>-scroll-offset widget))
         (visible-count (tree-view-visible-row-count widget))
         (selected (<tree-view>-selected-node widget))
         (border-width (if (<widget>-focused widget)
                           2
                           1))
         (border-color (if (<widget>-focused widget)
                           (<widget-style>-focus-border-color style)
                           (<widget-style>-border-color style))))
    (normalize-tree-view-scroll-offset widget)
    (setf scroll-offset (<tree-view>-scroll-offset widget))
    (fill-rect renderer x y w h (<widget-style>-background-color style))
    (stroke-rect renderer x y w h border-color border-width)
    (loop for (node depth) in (nthcdr scroll-offset rows)
          for index from 0
          while (< index visible-count)
          for row-y = (+ y (* index row-height))
          for content-y = (+ row-y (max 0 (floor (- row-height +font-text-height+) 2)))
          for row-x = (+ x (<widget-style>-text-padding style) (* depth indent))
          for tree-marker = (if (tree-node-has-children-p node)
                                (if (<tree-node>-expanded-p node) "v" ">")
                                " ")
          for kind-marker = (cond ((<tree-node>-directory-p node) "[D]")
                                  ((<tree-node>-file-p node) "[F]")
                                  (t "[ ]"))
          do (progn
               (when (eq node selected)
                 (fill-rect renderer (+ x 1) row-y (- w 2) row-height (<widget-style>-highlight-color style)))
               (render-text renderer
                            tree-marker
                            row-x
                            content-y
                            (<widget-style>-text-color style))
               (render-text renderer
                            (format nil "~A ~A" kind-marker (<tree-node>-text node))
                            (+ row-x 12)
                            content-y
                            (if (enabled-p widget)
                                (<widget-style>-text-color style)
                                (<widget-style>-disabled-color style)))))
    (when (tree-view-scrollbar-needed-p widget)
      (multiple-value-bind (needed-p track-x track-y track-height thumb-y thumb-height max-offset)
          (tree-view-scrollbar-geometry widget)
        (declare (ignore needed-p max-offset))
        (fill-rect renderer track-x track-y (<widget-style>-scrollbar-width style) track-height (<widget-style>-scrollbar-track-color style))
        (stroke-rect renderer track-x track-y (<widget-style>-scrollbar-width style) track-height (<widget-style>-scrollbar-thumb-color style))
        (fill-rect renderer (+ track-x 1) thumb-y (- (<widget-style>-scrollbar-width style) 2) thumb-height (<widget-style>-scrollbar-thumb-color style))
        (stroke-rect renderer (+ track-x 1) thumb-y (- (<widget-style>-scrollbar-width style) 2) thumb-height (<widget-style>-scrollbar-thumb-border-color style))))))

(defmethod render (renderer (widget <list-box>) style)
  (normalize-list-box-scroll-offset widget)
  (let* ((items (list-box-items widget))
         (scrollbar-width (<widget-style>-scrollbar-width style))
         (visible-count (list-box-visible-item-count widget))
         (item-count (length items))
         (scrollbar-needed-p (list-box-scrollbar-needed-p widget))
         (content-width (list-box-content-width widget))
         (scroll-offset (scroll-offset widget)))
    (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) (<widget>-height widget)
               (<widget-style>-background-color style))
    (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                 (<widget>-width widget) (<widget>-height widget)
                 (<widget-style>-border-color style))
    (loop for i from scroll-offset below (min item-count (+ scroll-offset visible-count))
          for item in (nthcdr scroll-offset items)
          for row from 0
          for item-y = (+ (<widget>-y widget) (* row (item-height widget)))
          do (progn
               (when (= i (selected-index widget))
                 (fill-rect renderer (<widget>-x widget) item-y
                            content-width (item-height widget)
                            (<widget-style>-highlight-color style)))
               (render-text renderer (format nil "~a" (item-display-value item))
                            (+ (<widget>-x widget) (<widget-style>-text-padding style))
                            (+ item-y (/ (- (item-height widget) +font-text-height+) 2))
                            (<widget-style>-text-color style))))
    (when scrollbar-needed-p
      (multiple-value-bind (needed-p track-x track-y track-height thumb-y thumb-height max-offset)
          (list-box-scrollbar-geometry widget)
        (declare (ignore needed-p max-offset))
        (fill-rect renderer track-x track-y scrollbar-width track-height (<widget-style>-scrollbar-track-color style))
        (stroke-rect renderer track-x track-y scrollbar-width track-height (<widget-style>-scrollbar-thumb-color style))
        (fill-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height (<widget-style>-scrollbar-thumb-color style))
        (stroke-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height (<widget-style>-scrollbar-thumb-border-color style))))))

(defun %render-combo-box-popup-at (renderer widget popup-x popup-y style)
  (normalize-combo-box-scroll-offset widget)
  (let* ((items (list-box-items widget))
         (scrollbar-width (<widget-style>-scrollbar-width style))
         (visible-count (combo-box-visible-item-count widget))
         (item-count (length items))
         (scrollbar-needed-p (combo-box-scrollbar-needed-p widget))
         (content-width (combo-box-content-width widget))
         (scroll-offset (scroll-offset widget))
         (popup-height (popup-height widget))
         (border-color (<widget-style>-border-color style))
         (popup-bg (<widget-style>-panel-background-color style))
         (track-bg (<widget-style>-scrollbar-track-color style))
         (thumb-bg (<widget-style>-scrollbar-thumb-color style))
         (thumb-border (<widget-style>-scrollbar-thumb-border-color style)))
    (fill-rect renderer popup-x popup-y
               (<widget>-width widget) popup-height popup-bg)
    (stroke-rect renderer popup-x popup-y
                 (<widget>-width widget) popup-height border-color)
    (loop for index from scroll-offset below (min item-count (+ scroll-offset visible-count))
          for item in (nthcdr scroll-offset items)
          for row from 0
          for item-y = (+ popup-y 1 (* row (item-height widget)))
          do (progn
               (when (= index (selected-index widget))
                 (fill-rect renderer popup-x item-y
                            content-width (item-height widget)
                            (<widget-style>-highlight-color style)))
               (render-text renderer (format nil "~a" (item-display-value item))
                            (+ popup-x (<widget-style>-text-padding style))
                            (+ item-y (/ (- (item-height widget) +font-text-height+) 2))
                            (<widget-style>-text-color style))))
    (when scrollbar-needed-p
      (multiple-value-bind (needed-p track-x track-y track-height thumb-y thumb-height max-offset)
          (scrollbar-geometry widget popup-x popup-y)
        (declare (ignore needed-p max-offset))
        (fill-rect renderer track-x track-y scrollbar-width track-height track-bg)
        (stroke-rect renderer track-x track-y scrollbar-width track-height border-color)
        (fill-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height thumb-bg)
        (stroke-rect renderer (+ track-x 1) thumb-y (- scrollbar-width 2) thumb-height thumb-border)))))

(defun %render-combo-box-popup (renderer widget style)
  (%render-combo-box-popup-at renderer widget
                              (<widget>-x widget)
                              (<widget>-y widget)
                              style))

(defun combo-box-header-focused-p (widget)
  (or (<widget>-focused widget)
      (and (<widget>-owner widget)
           (<widget>-focused (<widget>-owner widget)))))

(defun combo-box-header-render-colors (widget style)
  (let* ((enabled (enabled-p widget))
         (focused (combo-box-header-focused-p widget))
         (bg-color (if enabled
                       (<widget-style>-panel-background-color style)
                       (<widget-style>-button-face-disabled-color style)))
         (border-color (if (and enabled focused)
                           (<widget-style>-focus-border-color style)
                           (<widget-style>-border-color style)))
         (text-color (if enabled
                         (<widget-style>-text-color style)
                         (<widget-style>-disabled-color style))))
    (values bg-color border-color text-color)))

(defun %render-combo-box-main (renderer widget style bg-color border-color arrow-width arrow-text offset-y &key border-width text-color arrow-color)
  (let* ((selected-item (selected-item widget))
         (<label> (if selected-item
                    (format nil "~a" selected-item)
                    ""))
         (text-height (nth-value 1 (widget-text-pixel-size <label>)))
         (main-height (main-height widget))
         (text-padding (<widget-style>-text-padding style))
         (arrow-offset-y (<widget-style>-combo-box-arrow-offset-y style)))
    (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) main-height
               bg-color)
    (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                 (<widget>-width widget) main-height
                 border-color
                 (or border-width 1))
    (stroke-rect renderer (- (+ (<widget>-x widget) (<widget>-width widget)) arrow-width)
                 (<widget>-y widget)
                 arrow-width
                 main-height
                 border-color)
    (render-text renderer <label>
                 (+ (<widget>-x widget) text-padding)
                 (+ (<widget>-y widget)
                    (max 0 (floor (- main-height text-height) 2)))
                 (or text-color (<widget-style>-text-color style)))
    (render-text renderer arrow-text
                 (+ (- (+ (<widget>-x widget) (<widget>-width widget)) arrow-width) 8)
                 (+ (<widget>-y widget) (or offset-y arrow-offset-y))
                 (or arrow-color (<widget-style>-text-color style)))))

(defun %render-combo-box-focus-outline (renderer widget style inset)
  (let* ((x (+ (<widget>-x widget) inset))
         (y (+ (<widget>-y widget) inset))
         (w (- (<widget>-width widget) (* 2 inset)))
         (h (- (main-height widget) (* 2 inset))))
    (when (and (> w 6) (> h 6))
      (stroke-rect renderer x y w h (<widget-style>-focus-border-color style) 2))))

(defmethod render (renderer (widget <combo-box-header>) (style <flat-widget-style>))
  (when *debug-combo-box-focus*
    (format t "[combo-box-header-render] flat focused=~S owner-focused=~S enabled=~S expanded=~S~%"
            (<widget>-focused widget)
            (and (<widget>-owner widget) (<widget>-focused (<widget>-owner widget)))
            (enabled-p widget) (expanded-p widget)))
  (multiple-value-bind (bg-color border-color text-color)
      (combo-box-header-render-colors widget style)
    (%render-combo-box-main renderer widget style
                            bg-color
                            border-color
                            (<widget-style>-combo-box-arrow-width style)
                            (if (expanded-p widget) "^" "v")
                            (<widget-style>-combo-box-arrow-offset-y style)
                            :border-width 1
                            :text-color text-color
                            :arrow-color text-color)
    (when (combo-box-header-focused-p widget)
      (%render-combo-box-focus-outline renderer widget style 1))))

(defmethod render (renderer (widget <combo-box-header>) (style <windows-widget-style>))
  (when *debug-combo-box-focus*
    (format t "[combo-box-header-render] windows focused=~S owner-focused=~S enabled=~S expanded=~S~%"
            (<widget>-focused widget)
            (and (<widget>-owner widget) (<widget>-focused (<widget>-owner widget)))
            (enabled-p widget) (expanded-p widget)))
  (multiple-value-bind (face border-color text-color)
      (combo-box-header-render-colors widget style)
    (let* ((x (<widget>-x widget))
           (y (<widget>-y widget))
           (w (<widget>-width widget))
           (h (main-height widget))
           (arrow-width 24))
      (fill-rect renderer x y w h face)
      (render-bevel-rect renderer x y w h +color-white+ +color-dark-gray+ 1)
      (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                         +color-medium-gray+ +color-darker-gray+ 1)
      (stroke-rect renderer (- (+ x w) arrow-width) y arrow-width h +color-dark-gray+)
      (%render-combo-box-main renderer widget style face
                              border-color
                              arrow-width
                              (if (expanded-p widget) "^" "v")
                              (<widget-style>-combo-box-arrow-offset-y style)
                              :border-width 0
                              :text-color text-color
                              :arrow-color text-color)
      (when (combo-box-header-focused-p widget)
        (%render-combo-box-focus-outline renderer widget style 1)))))

(defmethod render (renderer (widget <combo-box-header>) (style <motif-widget-style>))
  (when *debug-combo-box-focus*
    (format t "[combo-box-header-render] motif focused=~S owner-focused=~S enabled=~S expanded=~S~%"
            (<widget>-focused widget)
            (and (<widget>-owner widget) (<widget>-focused (<widget>-owner widget)))
            (enabled-p widget) (expanded-p widget)))
  (multiple-value-bind (face border-color text-color)
      (combo-box-header-render-colors widget style)
    (let* ((x (<widget>-x widget))
           (y (<widget>-y widget))
           (w (<widget>-width widget))
           (h (main-height widget))
           (arrow-width 24))
      (fill-rect renderer x y w h face)
      (render-bevel-rect renderer x y w h +color-motif-light+ +color-motif-dark+ 2)
      (stroke-rect renderer (- (+ x w) arrow-width) y arrow-width h +color-motif-border+)
      (%render-combo-box-main renderer widget style face
                              border-color
                              arrow-width
                              (if (expanded-p widget) "^" "v")
                              (<widget-style>-combo-box-arrow-offset-y style)
                              :border-width 0
                              :text-color text-color
                              :arrow-color text-color)
      (when (combo-box-header-focused-p widget)
        (%render-combo-box-focus-outline renderer widget style 1)))))

(defmethod render (renderer (widget <combo-box>) (style <widget-style>))
  (when (header-widget widget)
    (render renderer (header-widget widget) style))
  (when (and (expanded-p widget)
             (popup-widget widget))
    (render renderer (popup-widget widget) style)))

(defun %render-editable-combo-box-main (renderer widget style bg-color border-color arrow-width arrow-text offset-y &key border-width)
  (let ((main-height (main-height widget)))
    (fill-rect renderer (<widget>-x widget) (<widget>-y widget)
               (<widget>-width widget) main-height
               bg-color)
    (stroke-rect renderer (<widget>-x widget) (<widget>-y widget)
                 (<widget>-width widget) main-height
                 border-color
                 (or border-width 1))
    (stroke-rect renderer (- (+ (<widget>-x widget) (<widget>-width widget)) arrow-width)
                 (<widget>-y widget)
                 arrow-width
                 main-height
                 border-color)
    (let ((text (<entry>-text widget))
          (placeholder (<editable-combo-box>-placeholder widget)))
      (if (and (zerop (length text)) (plusp (length placeholder))
               (not (<widget>-focused widget)))
          (render-text renderer placeholder
                       (+ (<widget>-x widget) (<widget-style>-text-padding style))
                       (+ (<widget>-y widget)
                          (/ (- main-height +font-text-height+) 2))
                       (<widget-style>-disabled-color style))
          (progn
            (let* ((text (<entry>-text widget))
                   (display-text (or (<entry>-show-text widget) text))
                   (text-x (+ (<widget>-x widget) (<widget-style>-text-padding style)))
                   (text-y (+ (<widget>-y widget)
                              (/ (- (<widget>-height widget) +font-text-height+) 2)))
                   (sel-start (<entry>-selection-start widget))
                   (sel-end (<entry>-selection-end widget))
                   (has-selection (and (not (null sel-start))
                                       (not (null sel-end))
                                       (< sel-start sel-end))))
              (multiple-value-bind (visible-start visible-end)
                  (<entry>-visible-range widget)
                (labels ((segment-x (position)
                           (+ text-x
                              (compute-text-segment-pixel-width widget visible-start position)))
                         (render-visible-segment (start end color)
                           (when (< start end)
                             (render-text renderer (subseq display-text start end)
                                          (segment-x start)
                                          text-y
                                          color))))
                  (if has-selection
                      (let ((before-start visible-start)
                            (before-end (min visible-end sel-start))
                            (selected-start (max visible-start sel-start))
                            (selected-end (min visible-end sel-end))
                            (after-start (max visible-start sel-end))
                            (after-end visible-end))
                        (render-visible-segment before-start before-end (<widget-style>-text-color style))
                        (when (< selected-start selected-end)
                          (let ((selection-x (segment-x selected-start))
                                (selection-w (compute-text-segment-pixel-width
                                              widget
                                              selected-start
                                              selected-end)))
                            (fill-rect renderer selection-x (- text-y (<widget-style>-selection-padding style))
                                       selection-w (+ +font-text-height+ (* 2 (<widget-style>-selection-padding style)))
                                       (<widget-style>-selection-background-color style))
                            (render-visible-segment selected-start selected-end
                                                    (<widget-style>-selection-text-color style))))
                        (render-visible-segment visible-start visible-end (<widget-style>-text-color style)))
                      (when (<widget>-focused widget)
                        (let ((cursor-x (segment-x (<entry>-cursor widget))))
                          (sdl3:set-render-draw-color renderer 0 0 0 255)
                          (sdl3:render-line renderer
                                            (float cursor-x 1.0)
                                            (float (+ (<widget>-y widget) (<widget-style>-cursor-offset style)) 1.0)
                                            (float cursor-x 1.0)
                                            (float (- (+ (<widget>-y widget)
                                                         (<widget>-height widget))
                                                      (<widget-style>-cursor-offset style))
                                                   1.0)))))))
              (render-text renderer arrow-text
                           (+ (- (+ (<widget>-x widget) (<widget>-width widget)) arrow-width) 8)
                           (+ (<widget>-y widget) offset-y)
                           (<widget-style>-text-color style))))))))

(defmethod render (renderer (widget <editable-combo-box>) (style <widget-style>))
  (let ((arrow-width (<widget-style>-combo-box-arrow-width style))
        (border-color (if (<widget>-focused widget)
                          (<widget-style>-focus-border-color style)
                          (<widget-style>-border-color style))))
    (%render-editable-combo-box-main renderer widget style
                                     (if (enabled-p widget)
                                         (<widget-style>-panel-background-color style)
                                         (<widget-style>-button-face-disabled-color style))
                                     border-color
                                     arrow-width
                                     (if (expanded-p widget) "^" "v")
                                     (<widget-style>-combo-box-arrow-offset-y style))
    (when (and (expanded-p widget)
               (not (<combo-box-popup>-window-enabled-p widget)))
      (%render-combo-box-popup renderer widget style))))

(defmethod render (renderer (widget <editable-combo-box>) (style <windows-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (main-height widget))
        (arrow-width 24)
        (face (if (enabled-p widget) +color-white+ +color-light-gray-2+)))
    (fill-rect renderer x y w h face)
    (render-bevel-rect renderer x y w h +color-white+ +color-dark-gray+ 1)
    (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                       +color-medium-gray+ +color-darker-gray+ 1)
    (stroke-rect renderer (- (+ x w) arrow-width) y arrow-width h +color-dark-gray+)
    (%render-editable-combo-box-main renderer widget style face
                                     (if (<widget>-focused widget)
                                         (<widget-style>-focus-border-color style)
                                         (<widget-style>-border-color style))
                                     arrow-width
                                     (if (expanded-p widget) "^" "v")
                                     (<widget-style>-combo-box-arrow-offset-y style)
                                     :border-width 0)
    (when (<widget>-focused widget)
      (%render-combo-box-focus-outline renderer widget 3)))
  (when (and (expanded-p widget)
             (not (<combo-box-popup>-window-enabled-p widget)))
    (%render-combo-box-popup renderer widget style)))

(defmethod render (renderer (widget <editable-combo-box>) (style <motif-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (main-height widget))
        (arrow-width 24)
        (face (if (enabled-p widget) +color-motif-light+ +color-medium-gray+)))
    (fill-rect renderer x y w h face)
    (render-bevel-rect renderer x y w h +color-motif-light+ +color-motif-dark+ 2)
    (stroke-rect renderer (- (+ x w) arrow-width) y arrow-width h +color-motif-border+)
    (%render-editable-combo-box-main renderer widget style face
                                     (if (<widget>-focused widget)
                                         (<widget-style>-focus-border-color style)
                                         (<widget-style>-border-color style))
                                     arrow-width
                                     (if (expanded-p widget) "^" "v")
                                     (<widget-style>-combo-box-arrow-offset-y style)
                                     :border-width 0)
    (when (<widget>-focused widget)
      (%render-combo-box-focus-outline renderer widget 4)))
  (when (and (expanded-p widget)
             (not (<combo-box-popup>-window-enabled-p widget)))
    (%render-combo-box-popup renderer widget style)))

;; popup rendering for combo-boxes that use separate popup windows.
;; Implemented as `render` methods on a transient `combo-box-popup` proxy
;; so popup windows are rendered after main widgets in `widgets-in-render-order`.

(defmethod render (renderer (popup <combo-box-popup>) (style <windows-widget-style>))
  (let ((owner (<widget>-owner popup)))
    (when owner
      (if (and (expanded-p owner)
               (<combo-box-popup>-window-enabled-p owner))
          (let* ((popup-renderer (or (popup-renderer popup)
                                     (popup-renderer owner)))
                 (visible-p (or (popup-visible-p popup)
                                (popup-visible-p owner))))
            (when (and (expanded-p owner)
                       (<combo-box-popup>-window-enabled-p owner)
                       (not visible-p))
              (show-popup-window owner))
            (when (and popup-renderer visible-p)
              (%render-combo-box-popup-at popup-renderer owner 0 0 style)
              (sdl3:render-present popup-renderer)))
          (when (expanded-p owner)
            (%render-combo-box-popup-at renderer owner
                                        (<widget>-x owner)
                                        (<widget>-y owner)
                                        style))))))

(defmethod render (renderer (popup <combo-box-popup>) (style <motif-widget-style>))
  (let ((owner (<widget>-owner popup)))
    (when owner
      (if (and (expanded-p owner)
               (<combo-box-popup>-window-enabled-p owner))
          (let* ((popup-renderer (or (popup-renderer popup)
                                     (popup-renderer owner)))
                 (visible-p (or (popup-visible-p popup)
                                (popup-visible-p owner))))
            (when (and (expanded-p owner)
                       (<combo-box-popup>-window-enabled-p owner)
                       (not visible-p))
              (show-popup-window owner))
            (when (and popup-renderer visible-p)
              (%render-combo-box-popup-at popup-renderer owner 0 0 style)
              (sdl3:render-present popup-renderer)))
          (when (expanded-p owner)
            (%render-combo-box-popup-at renderer owner
                                        (<widget>-x owner)
                                        (<widget>-y owner)
                                        style))))))

(defmethod render (renderer (popup <combo-box-popup>) style)
  (let ((owner (<widget>-owner popup)))
    (when owner
      (if (and (expanded-p owner)
               (<combo-box-popup>-window-enabled-p owner))
          (let* ((popup-renderer (or (popup-renderer popup)
                                     (popup-renderer owner)))
                 (visible-p (or (popup-visible-p popup)
                                (popup-visible-p owner))))
            (when (and (expanded-p owner)
                       (<combo-box-popup>-window-enabled-p owner)
                       (not visible-p))
              (show-popup-window owner))
            (when (and popup-renderer visible-p)
              (%render-combo-box-popup-at popup-renderer owner 0 0 style)
              (sdl3:render-present popup-renderer)))
          (when (expanded-p owner)
            (%render-combo-box-popup-at renderer owner
                                        (<widget>-x owner)
                                        (<widget>-y owner)
                                        style))))))

(defmethod render (renderer (popup <combo-box-popup>) (style <flat-widget-style>))
  (declare (ignore style))
  (render renderer popup (make-instance '<flat-widget-style>)))

(defmethod render (renderer (widget <button>) (style <windows-widget-style>))
  (declare (ignore style))
  (let* ((x (<widget>-x widget))
         (y (<widget>-y widget))
         (w (<widget>-width widget))
         (h (main-height widget))
         (arrow-width 24)
         (face (if (enabled-p widget) +color-motif-light+ +color-medium-gray+)))
    (fill-rect renderer x y w h face)
    (render-bevel-rect renderer x y w h +color-motif-light+ +color-motif-dark+ 2)
    (stroke-rect renderer (- (+ x w) arrow-width) y arrow-width h +color-motif-border+)
    (%render-combo-box-main renderer widget style face
                            (if (<widget>-focused widget) +color-focus-border+ +color-motif-border+)
                            arrow-width
                            (if (expanded-p widget) "^" "v")
                            (<widget-style>-combo-box-arrow-offset-y style)
                            :border-width 0)
    (when (<widget>-focused widget)
      (%render-combo-box-focus-outline renderer widget 4)))
  (when (expanded-p widget)
    (%render-combo-box-popup renderer widget style)))

(defmethod render (renderer (widget <button>) (style <windows-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (<widget>-height widget))
        (pressed (<button>-pressed-p widget))
        (face (if (enabled-p widget)
                  (<widget-style>-button-face-color style)
                  (<widget-style>-button-face-disabled-color style))))
    (fill-rect renderer x y w h face)
    (if pressed
        (progn
          (render-bevel-rect renderer x y w h +color-dark-gray+ +color-white+ 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             +color-darker-gray+ +color-light-gray+ 1))
        (progn
          (render-bevel-rect renderer x y w h +color-white+ +color-dark-gray+ 1)
          (render-bevel-rect renderer (+ x 1) (+ y 1) (- w 2) (- h 2)
                             +color-light-gray+ +color-darker-gray+ 1)))
    (when (<widget>-focused widget)
      (render-button-focus-outline renderer widget :inset 2)))
  (render-button-label renderer widget
                       (if (enabled-p widget)
                           (<widget-style>-text-color style)
                           (<widget-style>-disabled-color style))
                       :offset-x (if (<button>-pressed-p widget) 1 0)
                       :offset-y (if (<button>-pressed-p widget) 1 0)))

(defmethod render (renderer (widget <button>) (style <motif-widget-style>))
  (let ((x (<widget>-x widget))
        (y (<widget>-y widget))
        (w (<widget>-width widget))
        (h (<widget>-height widget))
        (pressed (<button>-pressed-p widget))
        (face (if (enabled-p widget)
                  (<widget-style>-button-face-color style)
                  (<widget-style>-button-face-disabled-color style))))
    (fill-rect renderer x y w h face)
    (if pressed
        (render-bevel-rect renderer x y w h +color-motif-dark+ +color-motif-light+ 2)
        (render-bevel-rect renderer x y w h +color-motif-light+ +color-motif-dark+ 2))
    (when (<widget>-focused widget)
      (render-button-focus-outline renderer widget :inset 4)))
  (render-button-label renderer widget
                       (if (enabled-p widget)
                           (<widget-style>-text-color style)
                           (<widget-style>-disabled-color style))
                       :offset-x (if (<button>-pressed-p widget) 1 0)
                       :offset-y (if (<button>-pressed-p widget) 1 0)))

(defmethod render :around ((renderer t) (popup <combo-box-popup>) style)
  (let ((owner (<widget>-owner popup)))
    (if (and owner
             (expanded-p owner)
             (<combo-box-popup>-window-enabled-p owner))
        (call-next-method)
        (when (visible-p popup)
          (call-next-method)))))
