;;;; ./src/widgets/methods/render.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod render (renderer (widget label))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             +color-bg+)
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               +color-border+)
  (render-text renderer (label-text widget)
               (+ (widget-x widget) +widget-padding+)
               (+ (widget-y widget) +widget-padding+)
               (if (widget-enabled widget) +color-text+ +color-disabled+)))

(defmethod render (renderer (widget button))
  (render-widget-with-style *widget-style* renderer widget))

(defmethod render (renderer (widget toggle))
  (let* ((toggle-width 40)
         (toggle-height 20)
         (toggle-x (widget-x widget))
         (toggle-y (+ (widget-y widget) (/ (- (widget-height widget) toggle-height) 2)))
         (circle-radius 8)
         (circle-cx (+ toggle-x circle-radius))
         (circle-cy (+ toggle-y circle-radius))
         (label-x (+ toggle-x toggle-width +widget-padding+ 5))
         (label-y (+ toggle-y (/ (- toggle-height +font-text-height+) 2))))
    (fill-circle renderer circle-cx circle-cy circle-radius +color-bg+)
    (stroke-circle renderer circle-cx circle-cy circle-radius +color-border+)
    (when (toggle-state widget)
      (fill-circle renderer circle-cx circle-cy 4 +color-text+))
    (when (widget-focused widget)
      (stroke-rect renderer (widget-x widget) (widget-y widget)
                   (widget-width widget) (widget-height widget)
                   +color-focus-border+ 1))
    (render-text renderer (toggle-label widget) label-x label-y +color-text+)))

(defmethod render (renderer (widget check-box))
  (let* ((box-size 16)
         (box-x (widget-x widget))
         (box-y (+ (widget-y widget) (/ (- (widget-height widget) box-size) 2))))
    (fill-rect renderer box-x box-y box-size box-size +color-bg+)
    (stroke-rect renderer box-x box-y box-size box-size +color-border+)
    (when (check-box-checked widget)
      (fill-rect renderer (+ box-x 3) (+ box-y 3) 10 10 +color-text+))
    (when (widget-focused widget)
      (stroke-rect renderer (widget-x widget) (widget-y widget)
                   (widget-width widget) (widget-height widget)
                   +color-focus-border+ 1))
    (render-text renderer (check-box-label widget)
                 (+ box-x box-size +widget-padding+)
                 (+ box-y (/ (- box-size +font-text-height+) 2))
                 +color-text+)))

(defmethod render (renderer (widget edit-box))
  (render-widget-with-style *widget-style* renderer widget))

(defmethod render (renderer (widget list-box))
  (fill-rect renderer (widget-x widget) (widget-y widget)
             (widget-width widget) (widget-height widget)
             +color-bg+)
  (stroke-rect renderer (widget-x widget) (widget-y widget)
               (widget-width widget) (widget-height widget)
               +color-border+)
  (loop for i from 0
        for item in (list-box-items widget)
        for item-y = (+ (widget-y widget) (* i (list-box-item-height widget)))
        while (< item-y (+ (widget-y widget) (widget-height widget)))
        do (progn
             (when (= i (list-box-selected-index widget))
               (fill-rect renderer (widget-x widget) item-y
                          (widget-width widget) (list-box-item-height widget)
                          +color-highlight+))
             (render-text renderer (format nil "~a" item)
                          (+ (widget-x widget) +widget-padding+)
                          (+ item-y (/ (- (list-box-item-height widget) +font-text-height+) 2))
                          +color-text+))))