;;;; ./src/widgets/methods/widget-measure.lisp

(in-package :mnas-sdl3-gui/widgets)

(defmethod widget-measure ((widget <widget>) &optional constraints)
  (declare (ignore constraints))
  (widget-min-size widget))

(defmethod widget-measure ((grid grid-container) &optional constraints)
  (declare (ignore constraints))
  (let* ((rows (max 1 (grid-rows grid)))
         (cols (max 1 (grid-cols grid)))
         (col-min (make-array cols :initial-element 0))
         (row-min (make-array rows :initial-element 0))
         (spacing-x (grid-col-spacing grid))
         (spacing-y (grid-row-spacing grid))
         (padding (grid-padding grid)))
    ;; accumulate minimal requirements taking spans into account
    (dolist (pair (grid-child-constraints grid))
      (let* ((child (car pair))
             (c (cdr pair)))
        (multiple-value-bind (min-w min-h) (widget-min-size child)
          (let* ((col (max 0 (min (1- cols) (grid-child-col c))))
                 (row (max 0 (min (1- rows) (grid-child-row c))))
                 (cspan (max 1 (min cols (grid-child-col-span c))))
                 (rspan (max 1 (min rows (grid-child-row-span c)))))
            (let* ((cur-w (reduce #'+ (subseq col-min col (min cols (+ col cspan))) :initial-value 0))
                   (cur-h (reduce #'+ (subseq row-min row (min rows (+ row rspan))) :initial-value 0)))
              (when (< cur-w min-w)
                (let* ((extra (- min-w cur-w))
                       (per (max 1 (floor (+ extra cspan -1) cspan))))
                  (loop for i from col below (min cols (+ col cspan)) do
                        (incf (aref col-min i) per))))
              (when (< cur-h min-h)
                (let* ((extra (- min-h cur-h))
                       (per (max 1 (floor (+ extra rspan -1) rspan))))
                  (loop for j from row below (min rows (+ row rspan)) do
                        (incf (aref row-min j) per)))))))))
    (let ((total-w (+ (* 2 padding) (reduce #'+ col-min) (* spacing-x (max 0 (1- cols)))))
          (total-h (+ (* 2 padding) (reduce #'+ row-min) (* spacing-y (max 0 (1- rows))))))
      (values (max 1 total-w) (max 1 total-h)))))
