(progn
  (ql:quickload :mnas-sdl3-gui/demos/dialog/pack-01)
  (let ((pkg (find-package "MNAS-SDL3-GUI/DEMOS/DIALOG/PACK-01")))
    (in-package :cl-user)
    (format t "package: ~S~%" pkg)
    (let* ((symbols '(pack-layout-demo-init pack-layout-demo-iterate pack-layout-demo-event pack-layout-demo-quit))
           (cffi-pkg (find-package "CFFI"))
           (get-callback-fn (and cffi-pkg (find-symbol "GET-CALLBACK" cffi-pkg))))
      (dolist (s symbols)
        (let* ((sym (intern (string-upcase (symbol-name s)) pkg))
               (fn (handler-case (symbol-function sym) (error (e) :no-fn)))
               (cb (if (and cffi-pkg get-callback-fn fn)
                       (handler-case (funcall (symbol-function (cdr get-callback-fn)) fn) (error (e) :error))
                       :no-cffi)))
          (format t "~S -> symbol-function: ~S~%" sym fn)
          (format t "~S -> cffi callback: ~S~%~%" sym cb))))
  (sb-ext:quit))
