(progn
  (ql:quickload :mnas-sdl3-gui)
  (format t "Loading grid-layout.lisp...~%")
  (load "/home/mna/quicklisp/local-projects/sdl3/mnas-sdl3-gui/src/widgets/methods/grid-layout.lisp")
  (let* ((pkg (find-package "MNAS-SDL3-GUI/WIDGETS"))
         (cls (find-class (intern "GRID-CONTAINER" pkg) nil))
         (wa (intern "WIDGET-ARRANGE" pkg)))
    (format t "grid-container class: ~S~%" cls)
        (format t "describe widget-arrange:~%")
        (describe (symbol-function wa))
        (let* ((spec (list cls t t t t))
         (m (find-method (symbol-function wa) nil spec)))
       (format t "find-method for grid-container: ~S~%" m))
    (format t "After reload widget-arrange methods:~%")
    (dolist (m (sb-mop:generic-function-methods (symbol-function wa)))
      (format t "METHOD: ~S~%  specializers: ~S~%  function: ~S~%~%" m (sb-mop:method-specializers m) (sb-mop:method-function m))))
  (sb-ext:quit))
